# Autogenerated via VCauto 0.6.00 (04/06/2011)

# Common defines
CC = gcc

AR = ar

CFLAGS = 

OBJDIR = Obj

# Include directories
INCLUDE_DIRS = -I . \
	-I C:/LinderdaumSDK/Src \
	-I C:/LinderdaumSDK/Src/Linderdaum \
	-I C:/LinderdaumSDK/Src/ExtLibs \
	-I Src \
	-I Src/ExtLibs \
	-I Src/ExtLibs/CL \
	-I Src/ExtLibs/DInput \
	-I Src/ExtLibs/FMOD \
	-I Src/ExtLibs/GL \
	-I Src/ExtLibs/ModPlug \
	-I Src/ExtLibs/OpenAL \
	-I Src/ExtLibs/RSC \
	-I Src/ExtLibs/Vorbis \
	-I Src/ExtLibs/Vorbis/ogg \
	-I Src/Generated \
	-I Src/Generated/Exports \
	-I Src/Generated/Globals \
	-I Src/Generated/LAL \
	-I Src/Generated/LCL \
	-I Src/Generated/LGL \
	-I Src/Generated/Serialization \
	-I Src/Generated/VM \
	-I Src/Linderdaum \
	-I Src/Linderdaum/Audio \
	-I Src/Linderdaum/Core \
	-I Src/Linderdaum/Core/RTTI \
	-I Src/Linderdaum/Core/VFS \
	-I Src/Linderdaum/Geometry \
	-I Src/Linderdaum/GUI \
	-I Src/Linderdaum/GUI/ComCtl \
	-I Src/Linderdaum/GUI/Transitions \
	-I Src/Linderdaum/Images \
	-I Src/Linderdaum/Input \
	-I Src/Linderdaum/Math \
	-I Src/Linderdaum/Network \
	-I Src/Linderdaum/Physics \
	-I Src/Linderdaum/Renderer \
	-I Src/Linderdaum/Renderer/CL \
	-I Src/Linderdaum/Renderer/DX11 \
	-I Src/Linderdaum/Renderer/GL \
	-I Src/Linderdaum/Renderer/Soft \
	-I Src/Linderdaum/Resources \
	-I Src/Linderdaum/Scene \
	-I Src/Linderdaum/Scene/Heightmaps \
	-I Src/Linderdaum/Scene/Particles \
	-I Src/Linderdaum/Scene/Postprocess \
	-I Src/Linderdaum/Scene/Terrain \
	-I Src/Linderdaum/UnitTests \
	-I Src/Linderdaum/UnitTests/Tests \
	-I Src/Linderdaum/Utils \
	-I Src/Linderdaum/VisualScene \
	-I Src/Linderdaum/World \
	-I Src/Linderdaum/World/AI \

COPTS = $(INCLUDE_DIRS)


# Object files list
OBJS =  \
	$(OBJDIR)/Exports_Core.o \
	$(OBJDIR)/ExpReg_Core1.o \
	$(OBJDIR)/ExpReg_Core2.o \
	$(OBJDIR)/ExpReg_Core3.o \
	$(OBJDIR)/ExpReg_Core4.o \
	$(OBJDIR)/ExpReg_Core5.o \
	$(OBJDIR)/ExpReg_Core6.o \
	$(OBJDIR)/ExpReg_Core7.o \
	$(OBJDIR)/ColorRegistration.o \
	$(OBJDIR)/KeySymbolsRegistration.o \
	$(OBJDIR)/LColors.o \
	$(OBJDIR)/LAL.o \
	$(OBJDIR)/LCL.o \
	$(OBJDIR)/LGL.o \
	$(OBJDIR)/LGLTracer.o \
	$(OBJDIR)/Serialization_LinderdaumCore.o \
	$(OBJDIR)/Audio.o \
	$(OBJDIR)/Audio_FMOD.o \
	$(OBJDIR)/Audio_OpenAL.o \
	$(OBJDIR)/MOD.o \
	$(OBJDIR)/OGG.o \
	$(OBJDIR)/Console.o \
	$(OBJDIR)/CVars.o \
	$(OBJDIR)/iObject.o \
	$(OBJDIR)/Linker.o \
	$(OBJDIR)/Logger.o \
	$(OBJDIR)/Field.o \
	$(OBJDIR)/iStaticClass.o \
	$(OBJDIR)/Property.o \
	$(OBJDIR)/State.o \
	$(OBJDIR)/Script.o \
	$(OBJDIR)/ScriptCompiler.o \
	$(OBJDIR)/UUID.o \
	$(OBJDIR)/Archive.o \
	$(OBJDIR)/Files.o \
	$(OBJDIR)/FileSystem.o \
	$(OBJDIR)/libcompress.o \
	$(OBJDIR)/ML.o \
	$(OBJDIR)/MountPoint.o \
	$(OBJDIR)/pugixml.o \
	$(OBJDIR)/Environment.o \
	$(OBJDIR)/Animation.o \
	$(OBJDIR)/ASE.o \
	$(OBJDIR)/Geom.o \
	$(OBJDIR)/GeomServ.o \
	$(OBJDIR)/Joints.o \
	$(OBJDIR)/LCM.o \
	$(OBJDIR)/MD5.o \
	$(OBJDIR)/Mesh.o \
	$(OBJDIR)/Surfaces.o \
	$(OBJDIR)/VAMender.o \
	$(OBJDIR)/VertexAttribs.o \
	$(OBJDIR)/I_BorderPanel.o \
	$(OBJDIR)/I_Bubbles.o \
	$(OBJDIR)/I_Button.o \
	$(OBJDIR)/I_Checkable.o \
	$(OBJDIR)/I_CheckBox.o \
	$(OBJDIR)/I_ColorDial.o \
	$(OBJDIR)/I_DialogWindow.o \
	$(OBJDIR)/I_FSGraph.o \
	$(OBJDIR)/I_Gauge.o \
	$(OBJDIR)/I_InputLine.o \
	$(OBJDIR)/I_ListBox.o \
	$(OBJDIR)/I_Memo.o \
	$(OBJDIR)/I_MtxView.o \
	$(OBJDIR)/I_Page.o \
	$(OBJDIR)/I_Panel.o \
	$(OBJDIR)/I_PushButton.o \
	$(OBJDIR)/I_RadioButton.o \
	$(OBJDIR)/I_RadioGroup.o \
	$(OBJDIR)/I_SceneView.o \
	$(OBJDIR)/I_Scroller.o \
	$(OBJDIR)/I_Sidebar.o \
	$(OBJDIR)/I_Slider.o \
	$(OBJDIR)/I_Splitters.o \
	$(OBJDIR)/I_StaticRect.o \
	$(OBJDIR)/I_StaticWidget.o \
	$(OBJDIR)/I_StdConsole.o \
	$(OBJDIR)/I_TabControl.o \
	$(OBJDIR)/I_TransitionPage.o \
	$(OBJDIR)/I_Window.o \
	$(OBJDIR)/FlowUI.o \
	$(OBJDIR)/GUIDesktop.o \
	$(OBJDIR)/GUIManager.o \
	$(OBJDIR)/iGUIRegion.o \
	$(OBJDIR)/iGUIResponder.o \
	$(OBJDIR)/iGUIView.o \
	$(OBJDIR)/I_CrossFade.o \
	$(OBJDIR)/I_Slide.o \
	$(OBJDIR)/Bitmap.o \
	$(OBJDIR)/FI_Utils.o \
	$(OBJDIR)/Guillotine.o \
	$(OBJDIR)/Image.o \
	$(OBJDIR)/ImageCache.o \
	$(OBJDIR)/ImageList.o \
	$(OBJDIR)/ImgLoad.o \
	$(OBJDIR)/RAW.o \
	$(OBJDIR)/TextRenderer.o \
	$(OBJDIR)/VolumeLib.o \
	$(OBJDIR)/Gestures.o \
	$(OBJDIR)/Gestures2.o \
	$(OBJDIR)/Input.o \
	$(OBJDIR)/NetDevices.o \
	$(OBJDIR)/OSInput.o \
	$(OBJDIR)/ScreenJoystick.o \
	$(OBJDIR)/LString.o \
	$(OBJDIR)/Collision.o \
	$(OBJDIR)/LAABB.o \
	$(OBJDIR)/LBox.o \
	$(OBJDIR)/LCurve.o \
	$(OBJDIR)/LFFT.o \
	$(OBJDIR)/LFrustum.o \
	$(OBJDIR)/LGeomUtils.o \
	$(OBJDIR)/LGraph.o \
	$(OBJDIR)/LMathStrings.o \
	$(OBJDIR)/LMatrix.o \
	$(OBJDIR)/LOBB.o \
	$(OBJDIR)/LPoly.o \
	$(OBJDIR)/LProjection.o \
	$(OBJDIR)/LRandom.o \
	$(OBJDIR)/LSphere.o \
	$(OBJDIR)/LTransform.o \
	$(OBJDIR)/LVector.o \
	$(OBJDIR)/HTTP.o \
	$(OBJDIR)/Network.o \
	$(OBJDIR)/BodyControllers.o \
	$(OBJDIR)/BoxLite.o \
	$(OBJDIR)/BoxScene.o \
	$(OBJDIR)/Collider.o \
	$(OBJDIR)/CollisionIntervals.o \
	$(OBJDIR)/CollisionShape.o \
	$(OBJDIR)/Control.o \
	$(OBJDIR)/RigidBody.o \
	$(OBJDIR)/SimplePhysics.o \
	$(OBJDIR)/Canvas.o \
	$(OBJDIR)/CLContext.o \
	$(OBJDIR)/DX11RenderContext.o \
	$(OBJDIR)/GLAPIContainer.o \
	$(OBJDIR)/GLBuffer.o \
	$(OBJDIR)/GLDebug.o \
	$(OBJDIR)/GLFrameBuffer.o \
	$(OBJDIR)/GLQuery.o \
	$(OBJDIR)/GLRenderContext.o \
	$(OBJDIR)/GLSL.o \
	$(OBJDIR)/GLTexture.o \
	$(OBJDIR)/GLVertexArray.o \
	$(OBJDIR)/iRenderContext.o \
	$(OBJDIR)/iShaderProgram.o \
	$(OBJDIR)/iTexture.o \
	$(OBJDIR)/iVertexArray.o \
	$(OBJDIR)/RenderState.o \
	$(OBJDIR)/SoftFrameBuffer.o \
	$(OBJDIR)/SoftRenderContext.o \
	$(OBJDIR)/VolumeRenderer.o \
	$(OBJDIR)/iResource.o \
	$(OBJDIR)/ResourcesManager.o \
	$(OBJDIR)/VFW.o \
	$(OBJDIR)/CSM.o \
	$(OBJDIR)/GameCamera.o \
	$(OBJDIR)/HeightMapFacetter.o \
	$(OBJDIR)/LHeightMap.o \
	$(OBJDIR)/iUpdater.o \
	$(OBJDIR)/LVLib.o \
	$(OBJDIR)/Material.o \
	$(OBJDIR)/GPUParticles.o \
	$(OBJDIR)/ParticleSystem.o \
	$(OBJDIR)/ASSAO.o \
	$(OBJDIR)/FeedbackScreen.o \
	$(OBJDIR)/Filter.o \
	$(OBJDIR)/HDRPP.o \
	$(OBJDIR)/iPostprocessor.o \
	$(OBJDIR)/MLAA.o \
	$(OBJDIR)/RenderingTechnique.o \
	$(OBJDIR)/Scene.o \
	$(OBJDIR)/Terrain.o \
	$(OBJDIR)/SysEnv.o \
	$(OBJDIR)/Tests.o \
	$(OBJDIR)/DateTime.o \
	$(OBJDIR)/Event.o \
	$(OBJDIR)/Exceptions.o \
	$(OBJDIR)/LArray.o \
	$(OBJDIR)/Library.o \
	$(OBJDIR)/Localizer.o \
	$(OBJDIR)/Screen.o \
	$(OBJDIR)/Thread.o \
	$(OBJDIR)/Utils.o \
	$(OBJDIR)/Viewport.o \
	$(OBJDIR)/CameraPositioner.o \
	$(OBJDIR)/Edit.o \
	$(OBJDIR)/Gizmos.o \
	$(OBJDIR)/Prefab.o \
	$(OBJDIR)/Trajectory.o \
	$(OBJDIR)/VisualCamera.o \
	$(OBJDIR)/VisualGraph.o \
	$(OBJDIR)/VisualObject.o \
	$(OBJDIR)/VisualProjector.o \
	$(OBJDIR)/VisualRenderables.o \
	$(OBJDIR)/VisualScene.o \
	$(OBJDIR)/Behaviour.o \
	$(OBJDIR)/Pathfinder.o \
	$(OBJDIR)/Entity.o \
	$(OBJDIR)/HighScores.o \
	$(OBJDIR)/iActor.o \
	$(OBJDIR)/World.o \

# Object files

$(OBJDIR)/Exports_Core.o: Src/Generated/Exports/Exports_Core.cpp Src/Generated/Exports/Exports_Core.h
	$(CC) $(COPTS) -MD -c Src/Generated/Exports/Exports_Core.cpp -o $(OBJDIR)/Exports_Core.o $(CFLAGS)

$(OBJDIR)/ExpReg_Core1.o: Src/Generated/Exports/ExpReg_Core1.cpp
	$(CC) $(COPTS) -MD -c Src/Generated/Exports/ExpReg_Core1.cpp -o $(OBJDIR)/ExpReg_Core1.o $(CFLAGS)

$(OBJDIR)/ExpReg_Core2.o: Src/Generated/Exports/ExpReg_Core2.cpp
	$(CC) $(COPTS) -MD -c Src/Generated/Exports/ExpReg_Core2.cpp -o $(OBJDIR)/ExpReg_Core2.o $(CFLAGS)

$(OBJDIR)/ExpReg_Core3.o: Src/Generated/Exports/ExpReg_Core3.cpp
	$(CC) $(COPTS) -MD -c Src/Generated/Exports/ExpReg_Core3.cpp -o $(OBJDIR)/ExpReg_Core3.o $(CFLAGS)

$(OBJDIR)/ExpReg_Core4.o: Src/Generated/Exports/ExpReg_Core4.cpp
	$(CC) $(COPTS) -MD -c Src/Generated/Exports/ExpReg_Core4.cpp -o $(OBJDIR)/ExpReg_Core4.o $(CFLAGS)

$(OBJDIR)/ExpReg_Core5.o: Src/Generated/Exports/ExpReg_Core5.cpp
	$(CC) $(COPTS) -MD -c Src/Generated/Exports/ExpReg_Core5.cpp -o $(OBJDIR)/ExpReg_Core5.o $(CFLAGS)

$(OBJDIR)/ExpReg_Core6.o: Src/Generated/Exports/ExpReg_Core6.cpp
	$(CC) $(COPTS) -MD -c Src/Generated/Exports/ExpReg_Core6.cpp -o $(OBJDIR)/ExpReg_Core6.o $(CFLAGS)

$(OBJDIR)/ExpReg_Core7.o: Src/Generated/Exports/ExpReg_Core7.cpp
	$(CC) $(COPTS) -MD -c Src/Generated/Exports/ExpReg_Core7.cpp -o $(OBJDIR)/ExpReg_Core7.o $(CFLAGS)

$(OBJDIR)/ColorRegistration.o: Src/Generated/Globals/ColorRegistration.cpp Src/Generated/Globals/ColorRegistration.h
	$(CC) $(COPTS) -MD -c Src/Generated/Globals/ColorRegistration.cpp -o $(OBJDIR)/ColorRegistration.o $(CFLAGS)

$(OBJDIR)/KeySymbolsRegistration.o: Src/Generated/Globals/KeySymbolsRegistration.cpp Src/Generated/Globals/KeySymbolsRegistration.h
	$(CC) $(COPTS) -MD -c Src/Generated/Globals/KeySymbolsRegistration.cpp -o $(OBJDIR)/KeySymbolsRegistration.o $(CFLAGS)

$(OBJDIR)/LColors.o: Src/Generated/Globals/LColors.cpp
	$(CC) $(COPTS) -MD -c Src/Generated/Globals/LColors.cpp -o $(OBJDIR)/LColors.o $(CFLAGS)

$(OBJDIR)/LAL.o: Src/Generated/LAL/LAL.cpp Src/Generated/LAL/LAL.h
	$(CC) $(COPTS) -MD -c Src/Generated/LAL/LAL.cpp -o $(OBJDIR)/LAL.o $(CFLAGS)

$(OBJDIR)/LCL.o: Src/Generated/LCL/LCL.cpp Src/Generated/LCL/LCL.h
	$(CC) $(COPTS) -MD -c Src/Generated/LCL/LCL.cpp -o $(OBJDIR)/LCL.o $(CFLAGS)

$(OBJDIR)/LGL.o: Src/Generated/LGL/LGL.cpp Src/Generated/LGL/LGL.h
	$(CC) $(COPTS) -MD -c Src/Generated/LGL/LGL.cpp -o $(OBJDIR)/LGL.o $(CFLAGS)

$(OBJDIR)/LGLTracer.o: Src/Generated/LGL/LGLTracer.cpp Src/Generated/LGL/LGLTracer.h
	$(CC) $(COPTS) -MD -c Src/Generated/LGL/LGLTracer.cpp -o $(OBJDIR)/LGLTracer.o $(CFLAGS)

$(OBJDIR)/Serialization_LinderdaumCore.o: Src/Generated/Serialization/Serialization_LinderdaumCore.cpp
	$(CC) $(COPTS) -MD -c Src/Generated/Serialization/Serialization_LinderdaumCore.cpp -o $(OBJDIR)/Serialization_LinderdaumCore.o $(CFLAGS)

$(OBJDIR)/Audio.o: Src/Linderdaum/Audio/Audio.cpp Src/Linderdaum/Audio/Audio.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Audio/Audio.cpp -o $(OBJDIR)/Audio.o $(CFLAGS)

$(OBJDIR)/Audio_FMOD.o: Src/Linderdaum/Audio/Audio_FMOD.cpp Src/Linderdaum/Audio/Audio_FMOD.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Audio/Audio_FMOD.cpp -o $(OBJDIR)/Audio_FMOD.o $(CFLAGS)

$(OBJDIR)/Audio_OpenAL.o: Src/Linderdaum/Audio/Audio_OpenAL.cpp Src/Linderdaum/Audio/Audio_OpenAL.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Audio/Audio_OpenAL.cpp -o $(OBJDIR)/Audio_OpenAL.o $(CFLAGS)

$(OBJDIR)/MOD.o: Src/Linderdaum/Audio/MOD.cpp Src/Linderdaum/Audio/MOD.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Audio/MOD.cpp -o $(OBJDIR)/MOD.o $(CFLAGS)

$(OBJDIR)/OGG.o: Src/Linderdaum/Audio/OGG.cpp Src/Linderdaum/Audio/OGG.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Audio/OGG.cpp -o $(OBJDIR)/OGG.o $(CFLAGS)

$(OBJDIR)/Console.o: Src/Linderdaum/Core/Console.cpp Src/Linderdaum/Core/Console.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/Console.cpp -o $(OBJDIR)/Console.o $(CFLAGS)

$(OBJDIR)/CVars.o: Src/Linderdaum/Core/CVars.cpp Src/Linderdaum/Core/CVars.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/CVars.cpp -o $(OBJDIR)/CVars.o $(CFLAGS)

$(OBJDIR)/iObject.o: Src/Linderdaum/Core/iObject.cpp Src/Linderdaum/Core/iObject.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/iObject.cpp -o $(OBJDIR)/iObject.o $(CFLAGS)

$(OBJDIR)/Linker.o: Src/Linderdaum/Core/Linker.cpp Src/Linderdaum/Core/Linker.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/Linker.cpp -o $(OBJDIR)/Linker.o $(CFLAGS)

$(OBJDIR)/Logger.o: Src/Linderdaum/Core/Logger.cpp Src/Linderdaum/Core/Logger.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/Logger.cpp -o $(OBJDIR)/Logger.o $(CFLAGS)

$(OBJDIR)/Field.o: Src/Linderdaum/Core/RTTI/Field.cpp Src/Linderdaum/Core/RTTI/Field.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/RTTI/Field.cpp -o $(OBJDIR)/Field.o $(CFLAGS)

$(OBJDIR)/iStaticClass.o: Src/Linderdaum/Core/RTTI/iStaticClass.cpp Src/Linderdaum/Core/RTTI/iStaticClass.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/RTTI/iStaticClass.cpp -o $(OBJDIR)/iStaticClass.o $(CFLAGS)

$(OBJDIR)/Property.o: Src/Linderdaum/Core/RTTI/Property.cpp Src/Linderdaum/Core/RTTI/Property.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/RTTI/Property.cpp -o $(OBJDIR)/Property.o $(CFLAGS)

$(OBJDIR)/State.o: Src/Linderdaum/Core/RTTI/State.cpp Src/Linderdaum/Core/RTTI/State.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/RTTI/State.cpp -o $(OBJDIR)/State.o $(CFLAGS)

$(OBJDIR)/Script.o: Src/Linderdaum/Core/Script.cpp Src/Linderdaum/Core/Script.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/Script.cpp -o $(OBJDIR)/Script.o $(CFLAGS)

$(OBJDIR)/ScriptCompiler.o: Src/Linderdaum/Core/ScriptCompiler.cpp Src/Linderdaum/Core/ScriptCompiler.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/ScriptCompiler.cpp -o $(OBJDIR)/ScriptCompiler.o $(CFLAGS)

$(OBJDIR)/UUID.o: Src/Linderdaum/Core/UUID.cpp Src/Linderdaum/Core/UUID.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/UUID.cpp -o $(OBJDIR)/UUID.o $(CFLAGS)

$(OBJDIR)/Archive.o: Src/Linderdaum/Core/VFS/Archive.cpp Src/Linderdaum/Core/VFS/Archive.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/VFS/Archive.cpp -o $(OBJDIR)/Archive.o $(CFLAGS)

$(OBJDIR)/Files.o: Src/Linderdaum/Core/VFS/Files.cpp Src/Linderdaum/Core/VFS/Files.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/VFS/Files.cpp -o $(OBJDIR)/Files.o $(CFLAGS)

$(OBJDIR)/FileSystem.o: Src/Linderdaum/Core/VFS/FileSystem.cpp Src/Linderdaum/Core/VFS/FileSystem.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/VFS/FileSystem.cpp -o $(OBJDIR)/FileSystem.o $(CFLAGS)

$(OBJDIR)/libcompress.o: Src/Linderdaum/Core/VFS/libcompress.c Src/Linderdaum/Core/VFS/libcompress.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/VFS/libcompress.c -o $(OBJDIR)/libcompress.o $(CFLAGS)

$(OBJDIR)/ML.o: Src/Linderdaum/Core/VFS/ML.cpp Src/Linderdaum/Core/VFS/ML.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/VFS/ML.cpp -o $(OBJDIR)/ML.o $(CFLAGS)

$(OBJDIR)/MountPoint.o: Src/Linderdaum/Core/VFS/MountPoint.cpp Src/Linderdaum/Core/VFS/MountPoint.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/VFS/MountPoint.cpp -o $(OBJDIR)/MountPoint.o $(CFLAGS)

$(OBJDIR)/pugixml.o: Src/Linderdaum/Core/VFS/pugixml.cpp
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Core/VFS/pugixml.cpp -o $(OBJDIR)/pugixml.o $(CFLAGS)

$(OBJDIR)/Environment.o: Src/Linderdaum/Environment.cpp Src/Linderdaum/Environment.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Environment.cpp -o $(OBJDIR)/Environment.o $(CFLAGS)

$(OBJDIR)/Animation.o: Src/Linderdaum/Geometry/Animation.cpp Src/Linderdaum/Geometry/Animation.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/Animation.cpp -o $(OBJDIR)/Animation.o $(CFLAGS)

$(OBJDIR)/ASE.o: Src/Linderdaum/Geometry/ASE.cpp Src/Linderdaum/Geometry/ASE.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/ASE.cpp -o $(OBJDIR)/ASE.o $(CFLAGS)

$(OBJDIR)/Geom.o: Src/Linderdaum/Geometry/Geom.cpp Src/Linderdaum/Geometry/Geom.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/Geom.cpp -o $(OBJDIR)/Geom.o $(CFLAGS)

$(OBJDIR)/GeomServ.o: Src/Linderdaum/Geometry/GeomServ.cpp Src/Linderdaum/Geometry/GeomServ.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/GeomServ.cpp -o $(OBJDIR)/GeomServ.o $(CFLAGS)

$(OBJDIR)/Joints.o: Src/Linderdaum/Geometry/Joints.cpp Src/Linderdaum/Geometry/Joints.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/Joints.cpp -o $(OBJDIR)/Joints.o $(CFLAGS)

$(OBJDIR)/LCM.o: Src/Linderdaum/Geometry/LCM.cpp Src/Linderdaum/Geometry/LCM.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/LCM.cpp -o $(OBJDIR)/LCM.o $(CFLAGS)

$(OBJDIR)/MD5.o: Src/Linderdaum/Geometry/MD5.cpp Src/Linderdaum/Geometry/MD5.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/MD5.cpp -o $(OBJDIR)/MD5.o $(CFLAGS)

$(OBJDIR)/Mesh.o: Src/Linderdaum/Geometry/Mesh.cpp Src/Linderdaum/Geometry/Mesh.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/Mesh.cpp -o $(OBJDIR)/Mesh.o $(CFLAGS)

$(OBJDIR)/Surfaces.o: Src/Linderdaum/Geometry/Surfaces.cpp Src/Linderdaum/Geometry/Surfaces.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/Surfaces.cpp -o $(OBJDIR)/Surfaces.o $(CFLAGS)

$(OBJDIR)/VAMender.o: Src/Linderdaum/Geometry/VAMender.cpp Src/Linderdaum/Geometry/VAMender.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/VAMender.cpp -o $(OBJDIR)/VAMender.o $(CFLAGS)

$(OBJDIR)/VertexAttribs.o: Src/Linderdaum/Geometry/VertexAttribs.cpp Src/Linderdaum/Geometry/VertexAttribs.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Geometry/VertexAttribs.cpp -o $(OBJDIR)/VertexAttribs.o $(CFLAGS)

$(OBJDIR)/I_BorderPanel.o: Src/Linderdaum/GUI/ComCtl/I_BorderPanel.cpp Src/Linderdaum/GUI/ComCtl/I_BorderPanel.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_BorderPanel.cpp -o $(OBJDIR)/I_BorderPanel.o $(CFLAGS)

$(OBJDIR)/I_Bubbles.o: Src/Linderdaum/GUI/ComCtl/I_Bubbles.cpp Src/Linderdaum/GUI/ComCtl/I_Bubbles.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Bubbles.cpp -o $(OBJDIR)/I_Bubbles.o $(CFLAGS)

$(OBJDIR)/I_Button.o: Src/Linderdaum/GUI/ComCtl/I_Button.cpp Src/Linderdaum/GUI/ComCtl/I_Button.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Button.cpp -o $(OBJDIR)/I_Button.o $(CFLAGS)

$(OBJDIR)/I_Checkable.o: Src/Linderdaum/GUI/ComCtl/I_Checkable.cpp Src/Linderdaum/GUI/ComCtl/I_Checkable.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Checkable.cpp -o $(OBJDIR)/I_Checkable.o $(CFLAGS)

$(OBJDIR)/I_CheckBox.o: Src/Linderdaum/GUI/ComCtl/I_CheckBox.cpp Src/Linderdaum/GUI/ComCtl/I_CheckBox.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_CheckBox.cpp -o $(OBJDIR)/I_CheckBox.o $(CFLAGS)

$(OBJDIR)/I_ColorDial.o: Src/Linderdaum/GUI/ComCtl/I_ColorDial.cpp Src/Linderdaum/GUI/ComCtl/I_ColorDial.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_ColorDial.cpp -o $(OBJDIR)/I_ColorDial.o $(CFLAGS)

$(OBJDIR)/I_DialogWindow.o: Src/Linderdaum/GUI/ComCtl/I_DialogWindow.cpp Src/Linderdaum/GUI/ComCtl/I_DialogWindow.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_DialogWindow.cpp -o $(OBJDIR)/I_DialogWindow.o $(CFLAGS)

$(OBJDIR)/I_FSGraph.o: Src/Linderdaum/GUI/ComCtl/I_FSGraph.cpp Src/Linderdaum/GUI/ComCtl/I_FSGraph.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_FSGraph.cpp -o $(OBJDIR)/I_FSGraph.o $(CFLAGS)

$(OBJDIR)/I_Gauge.o: Src/Linderdaum/GUI/ComCtl/I_Gauge.cpp Src/Linderdaum/GUI/ComCtl/I_Gauge.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Gauge.cpp -o $(OBJDIR)/I_Gauge.o $(CFLAGS)

$(OBJDIR)/I_InputLine.o: Src/Linderdaum/GUI/ComCtl/I_InputLine.cpp Src/Linderdaum/GUI/ComCtl/I_InputLine.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_InputLine.cpp -o $(OBJDIR)/I_InputLine.o $(CFLAGS)

$(OBJDIR)/I_ListBox.o: Src/Linderdaum/GUI/ComCtl/I_ListBox.cpp Src/Linderdaum/GUI/ComCtl/I_ListBox.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_ListBox.cpp -o $(OBJDIR)/I_ListBox.o $(CFLAGS)

$(OBJDIR)/I_Memo.o: Src/Linderdaum/GUI/ComCtl/I_Memo.cpp Src/Linderdaum/GUI/ComCtl/I_Memo.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Memo.cpp -o $(OBJDIR)/I_Memo.o $(CFLAGS)

$(OBJDIR)/I_MtxView.o: Src/Linderdaum/GUI/ComCtl/I_MtxView.cpp Src/Linderdaum/GUI/ComCtl/I_MtxView.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_MtxView.cpp -o $(OBJDIR)/I_MtxView.o $(CFLAGS)

$(OBJDIR)/I_Page.o: Src/Linderdaum/GUI/ComCtl/I_Page.cpp Src/Linderdaum/GUI/ComCtl/I_Page.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Page.cpp -o $(OBJDIR)/I_Page.o $(CFLAGS)

$(OBJDIR)/I_Panel.o: Src/Linderdaum/GUI/ComCtl/I_Panel.cpp Src/Linderdaum/GUI/ComCtl/I_Panel.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Panel.cpp -o $(OBJDIR)/I_Panel.o $(CFLAGS)

$(OBJDIR)/I_PushButton.o: Src/Linderdaum/GUI/ComCtl/I_PushButton.cpp Src/Linderdaum/GUI/ComCtl/I_PushButton.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_PushButton.cpp -o $(OBJDIR)/I_PushButton.o $(CFLAGS)

$(OBJDIR)/I_RadioButton.o: Src/Linderdaum/GUI/ComCtl/I_RadioButton.cpp Src/Linderdaum/GUI/ComCtl/I_RadioButton.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_RadioButton.cpp -o $(OBJDIR)/I_RadioButton.o $(CFLAGS)

$(OBJDIR)/I_RadioGroup.o: Src/Linderdaum/GUI/ComCtl/I_RadioGroup.cpp Src/Linderdaum/GUI/ComCtl/I_RadioGroup.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_RadioGroup.cpp -o $(OBJDIR)/I_RadioGroup.o $(CFLAGS)

$(OBJDIR)/I_SceneView.o: Src/Linderdaum/GUI/ComCtl/I_SceneView.cpp Src/Linderdaum/GUI/ComCtl/I_SceneView.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_SceneView.cpp -o $(OBJDIR)/I_SceneView.o $(CFLAGS)

$(OBJDIR)/I_Scroller.o: Src/Linderdaum/GUI/ComCtl/I_Scroller.cpp Src/Linderdaum/GUI/ComCtl/I_Scroller.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Scroller.cpp -o $(OBJDIR)/I_Scroller.o $(CFLAGS)

$(OBJDIR)/I_Sidebar.o: Src/Linderdaum/GUI/ComCtl/I_Sidebar.cpp Src/Linderdaum/GUI/ComCtl/I_Sidebar.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Sidebar.cpp -o $(OBJDIR)/I_Sidebar.o $(CFLAGS)

$(OBJDIR)/I_Slider.o: Src/Linderdaum/GUI/ComCtl/I_Slider.cpp Src/Linderdaum/GUI/ComCtl/I_Slider.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Slider.cpp -o $(OBJDIR)/I_Slider.o $(CFLAGS)

$(OBJDIR)/I_Splitters.o: Src/Linderdaum/GUI/ComCtl/I_Splitters.cpp Src/Linderdaum/GUI/ComCtl/I_Splitters.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Splitters.cpp -o $(OBJDIR)/I_Splitters.o $(CFLAGS)

$(OBJDIR)/I_StaticRect.o: Src/Linderdaum/GUI/ComCtl/I_StaticRect.cpp Src/Linderdaum/GUI/ComCtl/I_StaticRect.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_StaticRect.cpp -o $(OBJDIR)/I_StaticRect.o $(CFLAGS)

$(OBJDIR)/I_StaticWidget.o: Src/Linderdaum/GUI/ComCtl/I_StaticWidget.cpp Src/Linderdaum/GUI/ComCtl/I_StaticWidget.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_StaticWidget.cpp -o $(OBJDIR)/I_StaticWidget.o $(CFLAGS)

$(OBJDIR)/I_StdConsole.o: Src/Linderdaum/GUI/ComCtl/I_StdConsole.cpp Src/Linderdaum/GUI/ComCtl/I_StdConsole.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_StdConsole.cpp -o $(OBJDIR)/I_StdConsole.o $(CFLAGS)

$(OBJDIR)/I_TabControl.o: Src/Linderdaum/GUI/ComCtl/I_TabControl.cpp Src/Linderdaum/GUI/ComCtl/I_TabControl.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_TabControl.cpp -o $(OBJDIR)/I_TabControl.o $(CFLAGS)

$(OBJDIR)/I_TransitionPage.o: Src/Linderdaum/GUI/ComCtl/I_TransitionPage.cpp Src/Linderdaum/GUI/ComCtl/I_TransitionPage.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_TransitionPage.cpp -o $(OBJDIR)/I_TransitionPage.o $(CFLAGS)

$(OBJDIR)/I_Window.o: Src/Linderdaum/GUI/ComCtl/I_Window.cpp Src/Linderdaum/GUI/ComCtl/I_Window.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/ComCtl/I_Window.cpp -o $(OBJDIR)/I_Window.o $(CFLAGS)

$(OBJDIR)/FlowUI.o: Src/Linderdaum/GUI/FlowUI.cpp Src/Linderdaum/GUI/FlowUI.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/FlowUI.cpp -o $(OBJDIR)/FlowUI.o $(CFLAGS)

$(OBJDIR)/GUIDesktop.o: Src/Linderdaum/GUI/GUIDesktop.cpp Src/Linderdaum/GUI/GUIDesktop.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/GUIDesktop.cpp -o $(OBJDIR)/GUIDesktop.o $(CFLAGS)

$(OBJDIR)/GUIManager.o: Src/Linderdaum/GUI/GUIManager.cpp Src/Linderdaum/GUI/GUIManager.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/GUIManager.cpp -o $(OBJDIR)/GUIManager.o $(CFLAGS)

$(OBJDIR)/iGUIRegion.o: Src/Linderdaum/GUI/iGUIRegion.cpp Src/Linderdaum/GUI/iGUIRegion.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/iGUIRegion.cpp -o $(OBJDIR)/iGUIRegion.o $(CFLAGS)

$(OBJDIR)/iGUIResponder.o: Src/Linderdaum/GUI/iGUIResponder.cpp Src/Linderdaum/GUI/iGUIResponder.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/iGUIResponder.cpp -o $(OBJDIR)/iGUIResponder.o $(CFLAGS)

$(OBJDIR)/iGUIView.o: Src/Linderdaum/GUI/iGUIView.cpp Src/Linderdaum/GUI/iGUIView.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/iGUIView.cpp -o $(OBJDIR)/iGUIView.o $(CFLAGS)

$(OBJDIR)/I_CrossFade.o: Src/Linderdaum/GUI/Transitions/I_CrossFade.cpp Src/Linderdaum/GUI/Transitions/I_CrossFade.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/Transitions/I_CrossFade.cpp -o $(OBJDIR)/I_CrossFade.o $(CFLAGS)

$(OBJDIR)/I_Slide.o: Src/Linderdaum/GUI/Transitions/I_Slide.cpp Src/Linderdaum/GUI/Transitions/I_Slide.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/GUI/Transitions/I_Slide.cpp -o $(OBJDIR)/I_Slide.o $(CFLAGS)

$(OBJDIR)/Bitmap.o: Src/Linderdaum/Images/Bitmap.cpp Src/Linderdaum/Images/Bitmap.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/Bitmap.cpp -o $(OBJDIR)/Bitmap.o $(CFLAGS)

$(OBJDIR)/FI_Utils.o: Src/Linderdaum/Images/FI_Utils.cpp Src/Linderdaum/Images/FI_Utils.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/FI_Utils.cpp -o $(OBJDIR)/FI_Utils.o $(CFLAGS)

$(OBJDIR)/Guillotine.o: Src/Linderdaum/Images/Guillotine.cpp Src/Linderdaum/Images/Guillotine.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/Guillotine.cpp -o $(OBJDIR)/Guillotine.o $(CFLAGS)

$(OBJDIR)/Image.o: Src/Linderdaum/Images/Image.cpp Src/Linderdaum/Images/Image.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/Image.cpp -o $(OBJDIR)/Image.o $(CFLAGS)

$(OBJDIR)/ImageCache.o: Src/Linderdaum/Images/ImageCache.cpp Src/Linderdaum/Images/ImageCache.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/ImageCache.cpp -o $(OBJDIR)/ImageCache.o $(CFLAGS)

$(OBJDIR)/ImageList.o: Src/Linderdaum/Images/ImageList.cpp Src/Linderdaum/Images/ImageList.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/ImageList.cpp -o $(OBJDIR)/ImageList.o $(CFLAGS)

$(OBJDIR)/ImgLoad.o: Src/Linderdaum/Images/ImgLoad.cpp Src/Linderdaum/Images/ImgLoad.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/ImgLoad.cpp -o $(OBJDIR)/ImgLoad.o $(CFLAGS)

$(OBJDIR)/RAW.o: Src/Linderdaum/Images/RAW.cpp Src/Linderdaum/Images/RAW.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/RAW.cpp -o $(OBJDIR)/RAW.o $(CFLAGS)

$(OBJDIR)/TextRenderer.o: Src/Linderdaum/Images/TextRenderer.cpp Src/Linderdaum/Images/TextRenderer.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/TextRenderer.cpp -o $(OBJDIR)/TextRenderer.o $(CFLAGS)

$(OBJDIR)/VolumeLib.o: Src/Linderdaum/Images/VolumeLib.cpp Src/Linderdaum/Images/VolumeLib.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Images/VolumeLib.cpp -o $(OBJDIR)/VolumeLib.o $(CFLAGS)

$(OBJDIR)/Gestures.o: Src/Linderdaum/Input/Gestures.cpp Src/Linderdaum/Input/Gestures.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Input/Gestures.cpp -o $(OBJDIR)/Gestures.o $(CFLAGS)

$(OBJDIR)/Gestures2.o: Src/Linderdaum/Input/Gestures2.cpp Src/Linderdaum/Input/Gestures2.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Input/Gestures2.cpp -o $(OBJDIR)/Gestures2.o $(CFLAGS)

$(OBJDIR)/Input.o: Src/Linderdaum/Input/Input.cpp Src/Linderdaum/Input/Input.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Input/Input.cpp -o $(OBJDIR)/Input.o $(CFLAGS)

$(OBJDIR)/NetDevices.o: Src/Linderdaum/Input/NetDevices.cpp Src/Linderdaum/Input/NetDevices.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Input/NetDevices.cpp -o $(OBJDIR)/NetDevices.o $(CFLAGS)

$(OBJDIR)/OSInput.o: Src/Linderdaum/Input/OSInput.cpp Src/Linderdaum/Input/OSInput.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Input/OSInput.cpp -o $(OBJDIR)/OSInput.o $(CFLAGS)

$(OBJDIR)/ScreenJoystick.o: Src/Linderdaum/Input/ScreenJoystick.cpp Src/Linderdaum/Input/ScreenJoystick.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Input/ScreenJoystick.cpp -o $(OBJDIR)/ScreenJoystick.o $(CFLAGS)

$(OBJDIR)/LString.o: Src/Linderdaum/LString.cpp Src/Linderdaum/LString.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/LString.cpp -o $(OBJDIR)/LString.o $(CFLAGS)

$(OBJDIR)/Collision.o: Src/Linderdaum/Math/Collision.cpp Src/Linderdaum/Math/Collision.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/Collision.cpp -o $(OBJDIR)/Collision.o $(CFLAGS)

$(OBJDIR)/LAABB.o: Src/Linderdaum/Math/LAABB.cpp Src/Linderdaum/Math/LAABB.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LAABB.cpp -o $(OBJDIR)/LAABB.o $(CFLAGS)

$(OBJDIR)/LBox.o: Src/Linderdaum/Math/LBox.cpp Src/Linderdaum/Math/LBox.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LBox.cpp -o $(OBJDIR)/LBox.o $(CFLAGS)

$(OBJDIR)/LCurve.o: Src/Linderdaum/Math/LCurve.cpp Src/Linderdaum/Math/LCurve.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LCurve.cpp -o $(OBJDIR)/LCurve.o $(CFLAGS)

$(OBJDIR)/LFFT.o: Src/Linderdaum/Math/LFFT.cpp Src/Linderdaum/Math/LFFT.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LFFT.cpp -o $(OBJDIR)/LFFT.o $(CFLAGS)

$(OBJDIR)/LFrustum.o: Src/Linderdaum/Math/LFrustum.cpp Src/Linderdaum/Math/LFrustum.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LFrustum.cpp -o $(OBJDIR)/LFrustum.o $(CFLAGS)

$(OBJDIR)/LGeomUtils.o: Src/Linderdaum/Math/LGeomUtils.cpp Src/Linderdaum/Math/LGeomUtils.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LGeomUtils.cpp -o $(OBJDIR)/LGeomUtils.o $(CFLAGS)

$(OBJDIR)/LGraph.o: Src/Linderdaum/Math/LGraph.cpp Src/Linderdaum/Math/LGraph.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LGraph.cpp -o $(OBJDIR)/LGraph.o $(CFLAGS)

$(OBJDIR)/LMathStrings.o: Src/Linderdaum/Math/LMathStrings.cpp Src/Linderdaum/Math/LMathStrings.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LMathStrings.cpp -o $(OBJDIR)/LMathStrings.o $(CFLAGS)

$(OBJDIR)/LMatrix.o: Src/Linderdaum/Math/LMatrix.cpp Src/Linderdaum/Math/LMatrix.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LMatrix.cpp -o $(OBJDIR)/LMatrix.o $(CFLAGS)

$(OBJDIR)/LOBB.o: Src/Linderdaum/Math/LOBB.cpp Src/Linderdaum/Math/LOBB.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LOBB.cpp -o $(OBJDIR)/LOBB.o $(CFLAGS)

$(OBJDIR)/LPoly.o: Src/Linderdaum/Math/LPoly.cpp Src/Linderdaum/Math/LPoly.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LPoly.cpp -o $(OBJDIR)/LPoly.o $(CFLAGS)

$(OBJDIR)/LProjection.o: Src/Linderdaum/Math/LProjection.cpp Src/Linderdaum/Math/LProjection.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LProjection.cpp -o $(OBJDIR)/LProjection.o $(CFLAGS)

$(OBJDIR)/LRandom.o: Src/Linderdaum/Math/LRandom.cpp Src/Linderdaum/Math/LRandom.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LRandom.cpp -o $(OBJDIR)/LRandom.o $(CFLAGS)

$(OBJDIR)/LSphere.o: Src/Linderdaum/Math/LSphere.cpp Src/Linderdaum/Math/LSphere.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LSphere.cpp -o $(OBJDIR)/LSphere.o $(CFLAGS)

$(OBJDIR)/LTransform.o: Src/Linderdaum/Math/LTransform.cpp Src/Linderdaum/Math/LTransform.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LTransform.cpp -o $(OBJDIR)/LTransform.o $(CFLAGS)

$(OBJDIR)/LVector.o: Src/Linderdaum/Math/LVector.cpp Src/Linderdaum/Math/LVector.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Math/LVector.cpp -o $(OBJDIR)/LVector.o $(CFLAGS)

$(OBJDIR)/HTTP.o: Src/Linderdaum/Network/HTTP.cpp Src/Linderdaum/Network/HTTP.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Network/HTTP.cpp -o $(OBJDIR)/HTTP.o $(CFLAGS)

$(OBJDIR)/Network.o: Src/Linderdaum/Network/Network.cpp Src/Linderdaum/Network/Network.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Network/Network.cpp -o $(OBJDIR)/Network.o $(CFLAGS)

$(OBJDIR)/BodyControllers.o: Src/Linderdaum/Physics/BodyControllers.cpp Src/Linderdaum/Physics/BodyControllers.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Physics/BodyControllers.cpp -o $(OBJDIR)/BodyControllers.o $(CFLAGS)

$(OBJDIR)/BoxLite.o: Src/Linderdaum/Physics/BoxLite.cpp Src/Linderdaum/Physics/BoxLite.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Physics/BoxLite.cpp -o $(OBJDIR)/BoxLite.o $(CFLAGS)

$(OBJDIR)/BoxScene.o: Src/Linderdaum/Physics/BoxScene.cpp Src/Linderdaum/Physics/BoxScene.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Physics/BoxScene.cpp -o $(OBJDIR)/BoxScene.o $(CFLAGS)

$(OBJDIR)/Collider.o: Src/Linderdaum/Physics/Collider.cpp Src/Linderdaum/Physics/Collider.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Physics/Collider.cpp -o $(OBJDIR)/Collider.o $(CFLAGS)

$(OBJDIR)/CollisionIntervals.o: Src/Linderdaum/Physics/CollisionIntervals.cpp Src/Linderdaum/Physics/CollisionIntervals.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Physics/CollisionIntervals.cpp -o $(OBJDIR)/CollisionIntervals.o $(CFLAGS)

$(OBJDIR)/CollisionShape.o: Src/Linderdaum/Physics/CollisionShape.cpp Src/Linderdaum/Physics/CollisionShape.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Physics/CollisionShape.cpp -o $(OBJDIR)/CollisionShape.o $(CFLAGS)

$(OBJDIR)/Control.o: Src/Linderdaum/Physics/Control.cpp Src/Linderdaum/Physics/Control.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Physics/Control.cpp -o $(OBJDIR)/Control.o $(CFLAGS)

$(OBJDIR)/RigidBody.o: Src/Linderdaum/Physics/RigidBody.cpp Src/Linderdaum/Physics/RigidBody.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Physics/RigidBody.cpp -o $(OBJDIR)/RigidBody.o $(CFLAGS)

$(OBJDIR)/SimplePhysics.o: Src/Linderdaum/Physics/SimplePhysics.cpp Src/Linderdaum/Physics/SimplePhysics.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Physics/SimplePhysics.cpp -o $(OBJDIR)/SimplePhysics.o $(CFLAGS)

$(OBJDIR)/Canvas.o: Src/Linderdaum/Renderer/Canvas.cpp Src/Linderdaum/Renderer/Canvas.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/Canvas.cpp -o $(OBJDIR)/Canvas.o $(CFLAGS)

$(OBJDIR)/CLContext.o: Src/Linderdaum/Renderer/CL/CLContext.cpp Src/Linderdaum/Renderer/CL/CLContext.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/CL/CLContext.cpp -o $(OBJDIR)/CLContext.o $(CFLAGS)

$(OBJDIR)/DX11RenderContext.o: Src/Linderdaum/Renderer/DX11/DX11RenderContext.cpp Src/Linderdaum/Renderer/DX11/DX11RenderContext.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/DX11/DX11RenderContext.cpp -o $(OBJDIR)/DX11RenderContext.o $(CFLAGS)

$(OBJDIR)/GLAPIContainer.o: Src/Linderdaum/Renderer/GL/GLAPIContainer.cpp Src/Linderdaum/Renderer/GL/GLAPIContainer.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/GL/GLAPIContainer.cpp -o $(OBJDIR)/GLAPIContainer.o $(CFLAGS)

$(OBJDIR)/GLBuffer.o: Src/Linderdaum/Renderer/GL/GLBuffer.cpp Src/Linderdaum/Renderer/GL/GLBuffer.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/GL/GLBuffer.cpp -o $(OBJDIR)/GLBuffer.o $(CFLAGS)

$(OBJDIR)/GLDebug.o: Src/Linderdaum/Renderer/GL/GLDebug.cpp Src/Linderdaum/Renderer/GL/GLDebug.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/GL/GLDebug.cpp -o $(OBJDIR)/GLDebug.o $(CFLAGS)

$(OBJDIR)/GLFrameBuffer.o: Src/Linderdaum/Renderer/GL/GLFrameBuffer.cpp Src/Linderdaum/Renderer/GL/GLFrameBuffer.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/GL/GLFrameBuffer.cpp -o $(OBJDIR)/GLFrameBuffer.o $(CFLAGS)

$(OBJDIR)/GLQuery.o: Src/Linderdaum/Renderer/GL/GLQuery.cpp Src/Linderdaum/Renderer/GL/GLQuery.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/GL/GLQuery.cpp -o $(OBJDIR)/GLQuery.o $(CFLAGS)

$(OBJDIR)/GLRenderContext.o: Src/Linderdaum/Renderer/GL/GLRenderContext.cpp Src/Linderdaum/Renderer/GL/GLRenderContext.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/GL/GLRenderContext.cpp -o $(OBJDIR)/GLRenderContext.o $(CFLAGS)

$(OBJDIR)/GLSL.o: Src/Linderdaum/Renderer/GL/GLSL.cpp Src/Linderdaum/Renderer/GL/GLSL.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/GL/GLSL.cpp -o $(OBJDIR)/GLSL.o $(CFLAGS)

$(OBJDIR)/GLTexture.o: Src/Linderdaum/Renderer/GL/GLTexture.cpp Src/Linderdaum/Renderer/GL/GLTexture.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/GL/GLTexture.cpp -o $(OBJDIR)/GLTexture.o $(CFLAGS)

$(OBJDIR)/GLVertexArray.o: Src/Linderdaum/Renderer/GL/GLVertexArray.cpp Src/Linderdaum/Renderer/GL/GLVertexArray.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/GL/GLVertexArray.cpp -o $(OBJDIR)/GLVertexArray.o $(CFLAGS)

$(OBJDIR)/iRenderContext.o: Src/Linderdaum/Renderer/iRenderContext.cpp Src/Linderdaum/Renderer/iRenderContext.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/iRenderContext.cpp -o $(OBJDIR)/iRenderContext.o $(CFLAGS)

$(OBJDIR)/iShaderProgram.o: Src/Linderdaum/Renderer/iShaderProgram.cpp Src/Linderdaum/Renderer/iShaderProgram.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/iShaderProgram.cpp -o $(OBJDIR)/iShaderProgram.o $(CFLAGS)

$(OBJDIR)/iTexture.o: Src/Linderdaum/Renderer/iTexture.cpp Src/Linderdaum/Renderer/iTexture.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/iTexture.cpp -o $(OBJDIR)/iTexture.o $(CFLAGS)

$(OBJDIR)/iVertexArray.o: Src/Linderdaum/Renderer/iVertexArray.cpp Src/Linderdaum/Renderer/iVertexArray.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/iVertexArray.cpp -o $(OBJDIR)/iVertexArray.o $(CFLAGS)

$(OBJDIR)/RenderState.o: Src/Linderdaum/Renderer/RenderState.cpp Src/Linderdaum/Renderer/RenderState.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/RenderState.cpp -o $(OBJDIR)/RenderState.o $(CFLAGS)

$(OBJDIR)/SoftFrameBuffer.o: Src/Linderdaum/Renderer/Soft/SoftFrameBuffer.cpp Src/Linderdaum/Renderer/Soft/SoftFrameBuffer.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/Soft/SoftFrameBuffer.cpp -o $(OBJDIR)/SoftFrameBuffer.o $(CFLAGS)

$(OBJDIR)/SoftRenderContext.o: Src/Linderdaum/Renderer/Soft/SoftRenderContext.cpp Src/Linderdaum/Renderer/Soft/SoftRenderContext.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/Soft/SoftRenderContext.cpp -o $(OBJDIR)/SoftRenderContext.o $(CFLAGS)

$(OBJDIR)/VolumeRenderer.o: Src/Linderdaum/Renderer/VolumeRenderer.cpp Src/Linderdaum/Renderer/VolumeRenderer.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Renderer/VolumeRenderer.cpp -o $(OBJDIR)/VolumeRenderer.o $(CFLAGS)

$(OBJDIR)/iResource.o: Src/Linderdaum/Resources/iResource.cpp Src/Linderdaum/Resources/iResource.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Resources/iResource.cpp -o $(OBJDIR)/iResource.o $(CFLAGS)

$(OBJDIR)/ResourcesManager.o: Src/Linderdaum/Resources/ResourcesManager.cpp Src/Linderdaum/Resources/ResourcesManager.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Resources/ResourcesManager.cpp -o $(OBJDIR)/ResourcesManager.o $(CFLAGS)

$(OBJDIR)/VFW.o: Src/Linderdaum/Resources/VFW.cpp Src/Linderdaum/Resources/VFW.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Resources/VFW.cpp -o $(OBJDIR)/VFW.o $(CFLAGS)

$(OBJDIR)/CSM.o: Src/Linderdaum/Scene/CSM.cpp Src/Linderdaum/Scene/CSM.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/CSM.cpp -o $(OBJDIR)/CSM.o $(CFLAGS)

$(OBJDIR)/GameCamera.o: Src/Linderdaum/Scene/GameCamera.cpp Src/Linderdaum/Scene/GameCamera.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/GameCamera.cpp -o $(OBJDIR)/GameCamera.o $(CFLAGS)

$(OBJDIR)/HeightMapFacetter.o: Src/Linderdaum/Scene/Heightmaps/HeightMapFacetter.cpp Src/Linderdaum/Scene/Heightmaps/HeightMapFacetter.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Heightmaps/HeightMapFacetter.cpp -o $(OBJDIR)/HeightMapFacetter.o $(CFLAGS)

$(OBJDIR)/LHeightMap.o: Src/Linderdaum/Scene/Heightmaps/LHeightMap.cpp Src/Linderdaum/Scene/Heightmaps/LHeightMap.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Heightmaps/LHeightMap.cpp -o $(OBJDIR)/LHeightMap.o $(CFLAGS)

$(OBJDIR)/iUpdater.o: Src/Linderdaum/Scene/iUpdater.cpp Src/Linderdaum/Scene/iUpdater.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/iUpdater.cpp -o $(OBJDIR)/iUpdater.o $(CFLAGS)

$(OBJDIR)/LVLib.o: Src/Linderdaum/Scene/LVLib.cpp Src/Linderdaum/Scene/LVLib.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/LVLib.cpp -o $(OBJDIR)/LVLib.o $(CFLAGS)

$(OBJDIR)/Material.o: Src/Linderdaum/Scene/Material.cpp Src/Linderdaum/Scene/Material.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Material.cpp -o $(OBJDIR)/Material.o $(CFLAGS)

$(OBJDIR)/GPUParticles.o: Src/Linderdaum/Scene/Particles/GPUParticles.cpp Src/Linderdaum/Scene/Particles/GPUParticles.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Particles/GPUParticles.cpp -o $(OBJDIR)/GPUParticles.o $(CFLAGS)

$(OBJDIR)/ParticleSystem.o: Src/Linderdaum/Scene/Particles/ParticleSystem.cpp Src/Linderdaum/Scene/Particles/ParticleSystem.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Particles/ParticleSystem.cpp -o $(OBJDIR)/ParticleSystem.o $(CFLAGS)

$(OBJDIR)/ASSAO.o: Src/Linderdaum/Scene/Postprocess/ASSAO.cpp Src/Linderdaum/Scene/Postprocess/ASSAO.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Postprocess/ASSAO.cpp -o $(OBJDIR)/ASSAO.o $(CFLAGS)

$(OBJDIR)/FeedbackScreen.o: Src/Linderdaum/Scene/Postprocess/FeedbackScreen.cpp Src/Linderdaum/Scene/Postprocess/FeedbackScreen.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Postprocess/FeedbackScreen.cpp -o $(OBJDIR)/FeedbackScreen.o $(CFLAGS)

$(OBJDIR)/Filter.o: Src/Linderdaum/Scene/Postprocess/Filter.cpp Src/Linderdaum/Scene/Postprocess/Filter.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Postprocess/Filter.cpp -o $(OBJDIR)/Filter.o $(CFLAGS)

$(OBJDIR)/HDRPP.o: Src/Linderdaum/Scene/Postprocess/HDRPP.cpp Src/Linderdaum/Scene/Postprocess/HDRPP.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Postprocess/HDRPP.cpp -o $(OBJDIR)/HDRPP.o $(CFLAGS)

$(OBJDIR)/iPostprocessor.o: Src/Linderdaum/Scene/Postprocess/iPostprocessor.cpp Src/Linderdaum/Scene/Postprocess/iPostprocessor.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Postprocess/iPostprocessor.cpp -o $(OBJDIR)/iPostprocessor.o $(CFLAGS)

$(OBJDIR)/MLAA.o: Src/Linderdaum/Scene/Postprocess/MLAA.cpp Src/Linderdaum/Scene/Postprocess/MLAA.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Postprocess/MLAA.cpp -o $(OBJDIR)/MLAA.o $(CFLAGS)

$(OBJDIR)/RenderingTechnique.o: Src/Linderdaum/Scene/Postprocess/RenderingTechnique.cpp Src/Linderdaum/Scene/Postprocess/RenderingTechnique.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Postprocess/RenderingTechnique.cpp -o $(OBJDIR)/RenderingTechnique.o $(CFLAGS)

$(OBJDIR)/Scene.o: Src/Linderdaum/Scene/Scene.cpp Src/Linderdaum/Scene/Scene.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Scene.cpp -o $(OBJDIR)/Scene.o $(CFLAGS)

$(OBJDIR)/Terrain.o: Src/Linderdaum/Scene/Terrain/Terrain.cpp Src/Linderdaum/Scene/Terrain/Terrain.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Scene/Terrain/Terrain.cpp -o $(OBJDIR)/Terrain.o $(CFLAGS)

$(OBJDIR)/SysEnv.o: Src/Linderdaum/SysEnv.cpp Src/Linderdaum/SysEnv.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/SysEnv.cpp -o $(OBJDIR)/SysEnv.o $(CFLAGS)

$(OBJDIR)/Tests.o: Src/Linderdaum/UnitTests/Tests.cpp Src/Linderdaum/UnitTests/Tests.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/UnitTests/Tests.cpp -o $(OBJDIR)/Tests.o $(CFLAGS)

$(OBJDIR)/DateTime.o: Src/Linderdaum/Utils/DateTime.cpp Src/Linderdaum/Utils/DateTime.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/DateTime.cpp -o $(OBJDIR)/DateTime.o $(CFLAGS)

$(OBJDIR)/Event.o: Src/Linderdaum/Utils/Event.cpp Src/Linderdaum/Utils/Event.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/Event.cpp -o $(OBJDIR)/Event.o $(CFLAGS)

$(OBJDIR)/Exceptions.o: Src/Linderdaum/Utils/Exceptions.cpp Src/Linderdaum/Utils/Exceptions.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/Exceptions.cpp -o $(OBJDIR)/Exceptions.o $(CFLAGS)

$(OBJDIR)/LArray.o: Src/Linderdaum/Utils/LArray.cpp Src/Linderdaum/Utils/LArray.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/LArray.cpp -o $(OBJDIR)/LArray.o $(CFLAGS)

$(OBJDIR)/Library.o: Src/Linderdaum/Utils/Library.cpp Src/Linderdaum/Utils/Library.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/Library.cpp -o $(OBJDIR)/Library.o $(CFLAGS)

$(OBJDIR)/Localizer.o: Src/Linderdaum/Utils/Localizer.cpp Src/Linderdaum/Utils/Localizer.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/Localizer.cpp -o $(OBJDIR)/Localizer.o $(CFLAGS)

$(OBJDIR)/Screen.o: Src/Linderdaum/Utils/Screen.cpp Src/Linderdaum/Utils/Screen.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/Screen.cpp -o $(OBJDIR)/Screen.o $(CFLAGS)

$(OBJDIR)/Thread.o: Src/Linderdaum/Utils/Thread.cpp Src/Linderdaum/Utils/Thread.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/Thread.cpp -o $(OBJDIR)/Thread.o $(CFLAGS)

$(OBJDIR)/Utils.o: Src/Linderdaum/Utils/Utils.cpp Src/Linderdaum/Utils/Utils.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/Utils.cpp -o $(OBJDIR)/Utils.o $(CFLAGS)

$(OBJDIR)/Viewport.o: Src/Linderdaum/Utils/Viewport.cpp Src/Linderdaum/Utils/Viewport.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/Utils/Viewport.cpp -o $(OBJDIR)/Viewport.o $(CFLAGS)

$(OBJDIR)/CameraPositioner.o: Src/Linderdaum/VisualScene/CameraPositioner.cpp Src/Linderdaum/VisualScene/CameraPositioner.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/CameraPositioner.cpp -o $(OBJDIR)/CameraPositioner.o $(CFLAGS)

$(OBJDIR)/Edit.o: Src/Linderdaum/VisualScene/Edit.cpp Src/Linderdaum/VisualScene/Edit.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/Edit.cpp -o $(OBJDIR)/Edit.o $(CFLAGS)

$(OBJDIR)/Gizmos.o: Src/Linderdaum/VisualScene/Gizmos.cpp Src/Linderdaum/VisualScene/Gizmos.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/Gizmos.cpp -o $(OBJDIR)/Gizmos.o $(CFLAGS)

$(OBJDIR)/Prefab.o: Src/Linderdaum/VisualScene/Prefab.cpp Src/Linderdaum/VisualScene/Prefab.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/Prefab.cpp -o $(OBJDIR)/Prefab.o $(CFLAGS)

$(OBJDIR)/Trajectory.o: Src/Linderdaum/VisualScene/Trajectory.cpp Src/Linderdaum/VisualScene/Trajectory.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/Trajectory.cpp -o $(OBJDIR)/Trajectory.o $(CFLAGS)

$(OBJDIR)/VisualCamera.o: Src/Linderdaum/VisualScene/VisualCamera.cpp Src/Linderdaum/VisualScene/VisualCamera.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/VisualCamera.cpp -o $(OBJDIR)/VisualCamera.o $(CFLAGS)

$(OBJDIR)/VisualGraph.o: Src/Linderdaum/VisualScene/VisualGraph.cpp Src/Linderdaum/VisualScene/VisualGraph.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/VisualGraph.cpp -o $(OBJDIR)/VisualGraph.o $(CFLAGS)

$(OBJDIR)/VisualObject.o: Src/Linderdaum/VisualScene/VisualObject.cpp Src/Linderdaum/VisualScene/VisualObject.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/VisualObject.cpp -o $(OBJDIR)/VisualObject.o $(CFLAGS)

$(OBJDIR)/VisualProjector.o: Src/Linderdaum/VisualScene/VisualProjector.cpp Src/Linderdaum/VisualScene/VisualProjector.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/VisualProjector.cpp -o $(OBJDIR)/VisualProjector.o $(CFLAGS)

$(OBJDIR)/VisualRenderables.o: Src/Linderdaum/VisualScene/VisualRenderables.cpp Src/Linderdaum/VisualScene/VisualRenderables.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/VisualRenderables.cpp -o $(OBJDIR)/VisualRenderables.o $(CFLAGS)

$(OBJDIR)/VisualScene.o: Src/Linderdaum/VisualScene/VisualScene.cpp Src/Linderdaum/VisualScene/VisualScene.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/VisualScene/VisualScene.cpp -o $(OBJDIR)/VisualScene.o $(CFLAGS)

$(OBJDIR)/Behaviour.o: Src/Linderdaum/World/AI/Behaviour.cpp Src/Linderdaum/World/AI/Behaviour.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/World/AI/Behaviour.cpp -o $(OBJDIR)/Behaviour.o $(CFLAGS)

$(OBJDIR)/Pathfinder.o: Src/Linderdaum/World/AI/Pathfinder.cpp Src/Linderdaum/World/AI/Pathfinder.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/World/AI/Pathfinder.cpp -o $(OBJDIR)/Pathfinder.o $(CFLAGS)

$(OBJDIR)/Entity.o: Src/Linderdaum/World/Entity.cpp Src/Linderdaum/World/Entity.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/World/Entity.cpp -o $(OBJDIR)/Entity.o $(CFLAGS)

$(OBJDIR)/HighScores.o: Src/Linderdaum/World/HighScores.cpp Src/Linderdaum/World/HighScores.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/World/HighScores.cpp -o $(OBJDIR)/HighScores.o $(CFLAGS)

$(OBJDIR)/iActor.o: Src/Linderdaum/World/iActor.cpp Src/Linderdaum/World/iActor.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/World/iActor.cpp -o $(OBJDIR)/iActor.o $(CFLAGS)

$(OBJDIR)/World.o: Src/Linderdaum/World/World.cpp Src/Linderdaum/World/World.h
	$(CC) $(COPTS) -MD -c Src/Linderdaum/World/World.cpp -o $(OBJDIR)/World.o $(CFLAGS)


# User-defined targets

USEDLIBS = -lgdi32 -lstdc++ -lmsvfw32

# CFLAGS = -m32 -fomit-frame-pointer -fpermissive -msse3 -s -O2

# Let's check if this is a faster at compile time
CFLAGS = -m32 -fomit-frame-pointer -fpermissive

####################
# Targets
####################

GAMEA: $(OBJS)
	rm -f Obj/Game.a
	ar -ru Obj/Game.a $(OBJS)

all: $(OBJS) GAMEA
#$(OBJS)
	$(CC) $(COPTS) $(CFLAGS) -o Test_Android.exe Src/Test_Android.cpp Obj/Game.a C:/LinderdaumSDK/Out/Obj/libLinderdaumEngine.a $(USEDLIBS)


# End of Makefile
