/**
 * \file LColors.h
 * \brief Standard colors [Autogenerated]
 * \version 0.5.91
 * \date 12/07/2010
 * \author Sergey Kosarevsky, 2005-2010
 * \author Viktor Latypov, 2007-2010
 * \author support@linderdaum.com http://www.linderdaum.com
 */

#ifndef _LColors_included_h_
#define _LColors_included_h_

#include "Platform.h"
#include "Math/LVector.h"

const LVector4 LC_Transparent          ( 0.000000f, 0.000000f, 0.000000f, 0.000000f );
const LVector4 LC_Black                ( 0.000000f, 0.000000f, 0.000000f, 1.000000f );
const LVector4 LC_Gray05               ( 0.050000f, 0.050000f, 0.050000f, 1.000000f );
const LVector4 LC_Gray10               ( 0.100000f, 0.100000f, 0.100000f, 1.000000f );
const LVector4 LC_Gray15               ( 0.150000f, 0.150000f, 0.150000f, 1.000000f );
const LVector4 LC_Gray20               ( 0.200000f, 0.200000f, 0.200000f, 1.000000f );
const LVector4 LC_Gray25               ( 0.250000f, 0.250000f, 0.250000f, 1.000000f );
const LVector4 LC_Gray30               ( 0.300000f, 0.300000f, 0.300000f, 1.000000f );
const LVector4 LC_Gray35               ( 0.350000f, 0.350000f, 0.350000f, 1.000000f );
const LVector4 LC_Gray40               ( 0.400000f, 0.400000f, 0.400000f, 1.000000f );
const LVector4 LC_Gray45               ( 0.450000f, 0.450000f, 0.450000f, 1.000000f );
const LVector4 LC_Gray50               ( 0.500000f, 0.500000f, 0.500000f, 1.000000f );
const LVector4 LC_Gray55               ( 0.550000f, 0.550000f, 0.550000f, 1.000000f );
const LVector4 LC_Gray60               ( 0.600000f, 0.600000f, 0.600000f, 1.000000f );
const LVector4 LC_Gray65               ( 0.650000f, 0.650000f, 0.650000f, 1.000000f );
const LVector4 LC_Gray70               ( 0.700000f, 0.700000f, 0.700000f, 1.000000f );
const LVector4 LC_Gray75               ( 0.750000f, 0.750000f, 0.750000f, 1.000000f );
const LVector4 LC_Gray80               ( 0.800000f, 0.800000f, 0.800000f, 1.000000f );
const LVector4 LC_Gray85               ( 0.850000f, 0.850000f, 0.850000f, 1.000000f );
const LVector4 LC_Gray90               ( 0.900000f, 0.900000f, 0.900000f, 1.000000f );
const LVector4 LC_Gray95               ( 0.950000f, 0.950000f, 0.950000f, 1.000000f );
const LVector4 LC_White                ( 1.000000f, 1.000000f, 1.000000f, 1.000000f );
// other grays
const LVector4 LC_DimGray              ( 0.329412f, 0.329412f, 0.329412f, 1.000000f );
const LVector4 LC_Gray                 ( 0.752941f, 0.752941f, 0.752941f, 1.000000f );
const LVector4 LC_LightGray            ( 0.658824f, 0.658824f, 0.658824f, 1.000000f );
// colors en masse
const LVector4 LC_Aquamarine           ( 0.439216f, 0.858824f, 0.576471f, 1.000000f );
const LVector4 LC_BlueViolet           ( 0.623520f, 0.372549f, 0.623529f, 1.000000f );
const LVector4 LC_Brown                ( 0.647059f, 0.164706f, 0.164706f, 1.000000f );
const LVector4 LC_CadetBlue            ( 0.372549f, 0.623529f, 0.623529f, 1.000000f );
const LVector4 LC_Coral                ( 1.000000f, 0.498039f, 0.000000f, 1.000000f );
const LVector4 LC_CornflowerBlue       ( 0.258824f, 0.258824f, 0.435294f, 1.000000f );
const LVector4 LC_DarkGreen            ( 0.184314f, 0.309804f, 0.184314f, 1.000000f );
const LVector4 LC_DarkOliveGreen       ( 0.309804f, 0.309804f, 0.184314f, 1.000000f );
const LVector4 LC_DarkOrchid           ( 0.600000f, 0.196078f, 0.800000f, 1.000000f );
const LVector4 LC_DarkSlateBlue        ( 0.419608f, 0.137255f, 0.556863f, 1.000000f );
const LVector4 LC_DarkSlateGray        ( 0.184314f, 0.309804f, 0.309804f, 1.000000f );
const LVector4 LC_DarkSlateGrey        ( 0.184314f, 0.309804f, 0.309804f, 1.000000f );
const LVector4 LC_DarkTurquoise        ( 0.439216f, 0.576471f, 0.858824f, 1.000000f );
const LVector4 LC_Firebrick            ( 0.556863f, 0.137255f, 0.137255f, 1.000000f );
const LVector4 LC_ForestGreen          ( 0.137255f, 0.556863f, 0.137255f, 1.000000f );
const LVector4 LC_Gold                 ( 0.800000f, 0.498039f, 0.196078f, 1.000000f );
const LVector4 LC_Goldenrod            ( 0.858824f, 0.858824f, 0.439216f, 1.000000f );
const LVector4 LC_GreenYellow          ( 0.576471f, 0.858824f, 0.439216f, 1.000000f );
const LVector4 LC_Indian               ( 0.309804f, 0.184314f, 0.184314f, 1.000000f );
const LVector4 LC_Khaki                ( 0.623529f, 0.623529f, 0.372549f, 1.000000f );
const LVector4 LC_LightBlue            ( 0.749020f, 0.847059f, 0.847059f, 1.000000f );
const LVector4 LC_LightSteelBlue       ( 0.560784f, 0.560784f, 0.737255f, 1.000000f );
const LVector4 LC_LimeGreen            ( 0.196078f, 0.800000f, 0.196078f, 1.000000f );
const LVector4 LC_Magenta              ( 1.000000f, 0.000000f, 1.000000f, 1.000000f );
const LVector4 LC_Maroon               ( 0.556863f, 0.137255f, 0.419608f, 1.000000f );
const LVector4 LC_MediumAquamarine     ( 0.196078f, 0.800000f, 0.600000f, 1.000000f );
const LVector4 LC_MediumBlue           ( 0.196078f, 0.196078f, 0.800000f, 1.000000f );
const LVector4 LC_MediumForestGreen    ( 0.419608f, 0.556863f, 0.137255f, 1.000000f );
const LVector4 LC_MediumGoldenrod      ( 0.917647f, 0.917647f, 0.678431f, 1.000000f );
const LVector4 LC_MediumOrchid         ( 0.576471f, 0.439216f, 0.858824f, 1.000000f );
const LVector4 LC_MediumSeaGreen       ( 0.258824f, 0.435294f, 0.258824f, 1.000000f );
const LVector4 LC_MediumSlateBlue      ( 0.498039f, 0.000000f, 1.000000f, 1.000000f );
const LVector4 LC_MediumSpringGreen    ( 0.498039f, 1.000000f, 0.000000f, 1.000000f );
const LVector4 LC_MediumTurquoise      ( 0.439216f, 0.858824f, 0.858824f, 1.000000f );
const LVector4 LC_MediumViolet         ( 0.858824f, 0.439216f, 0.576471f, 1.000000f );
const LVector4 LC_MidnightBlue         ( 0.184314f, 0.184314f, 0.309804f, 1.000000f );
const LVector4 LC_Navy                 ( 0.137255f, 0.137255f, 0.556863f, 1.000000f );
const LVector4 LC_NavyBlue             ( 0.137255f, 0.137255f, 0.556863f, 1.000000f );
const LVector4 LC_Orange               ( 1.000000f, 0.500000f, 0.000000f, 1.000000f );
const LVector4 LC_OrangeRed            ( 1.000000f, 0.250000f, 0.000000f, 1.000000f );
const LVector4 LC_Orchid               ( 0.858824f, 0.439216f, 0.858824f, 1.000000f );
const LVector4 LC_PaleGreen            ( 0.560784f, 0.737255f, 0.560784f, 1.000000f );
const LVector4 LC_Pink                 ( 0.737255f, 0.560784f, 0.560784f, 1.000000f );
const LVector4 LC_Plum                 ( 0.917647f, 0.678431f, 0.917647f, 1.000000f );
const LVector4 LC_Salmon               ( 0.435294f, 0.258824f, 0.258824f, 1.000000f );
const LVector4 LC_SeaGreen             ( 0.137255f, 0.556863f, 0.419608f, 1.000000f );
const LVector4 LC_Sienna               ( 0.556863f, 0.419608f, 0.137255f, 1.000000f );
const LVector4 LC_SkyBlue              ( 0.196078f, 0.600000f, 0.800000f, 1.000000f );
const LVector4 LC_SlateBlue            ( 0.000000f, 0.498039f, 1.000000f, 1.000000f );
const LVector4 LC_SpringGreen          ( 0.000000f, 1.000000f, 0.498039f, 1.000000f );
const LVector4 LC_SteelBlue            ( 0.137255f, 0.419608f, 0.556863f, 1.000000f );
const LVector4 LC_Tan                  ( 0.858824f, 0.576471f, 0.439216f, 1.000000f );
const LVector4 LC_Thistle              ( 0.847059f, 0.749020f, 0.847059f, 1.000000f );
const LVector4 LC_Turquoise            ( 0.678431f, 0.917647f, 0.917647f, 1.000000f );
const LVector4 LC_Violet               ( 0.309804f, 0.184314f, 0.309804f, 1.000000f );
const LVector4 LC_VioletRed            ( 0.800000f, 0.196078f, 0.600000f, 1.000000f );
const LVector4 LC_Wheat                ( 0.847059f, 0.847059f, 0.749020f, 1.000000f );
const LVector4 LC_YellowGreen          ( 0.600000f, 0.800000f, 0.196078f, 1.000000f );
const LVector4 LC_SummerSky            ( 0.220000f, 0.690000f, 0.870000f, 1.000000f );
const LVector4 LC_RichBlue             ( 0.350000f, 0.350000f, 0.670000f, 1.000000f );
const LVector4 LC_Brass                ( 0.710000f, 0.650000f, 0.260000f, 1.000000f );
const LVector4 LC_Copper               ( 0.720000f, 0.450000f, 0.200000f, 1.000000f );
const LVector4 LC_Bronze               ( 0.550000f, 0.470000f, 0.140000f, 1.000000f );
const LVector4 LC_Bronze2              ( 0.650000f, 0.490000f, 0.240000f, 1.000000f );
const LVector4 LC_Silver               ( 0.900000f, 0.910000f, 0.980000f, 1.000000f );
const LVector4 LC_BrightGold           ( 0.850000f, 0.850000f, 0.100000f, 1.000000f );
const LVector4 LC_OldGold              ( 0.810000f, 0.710000f, 0.230000f, 1.000000f );
const LVector4 LC_Feldspar             ( 0.820000f, 0.570000f, 0.460000f, 1.000000f );
const LVector4 LC_Quartz               ( 0.850000f, 0.850000f, 0.950000f, 1.000000f );
const LVector4 LC_NeonPink             ( 1.000000f, 0.430000f, 0.780000f, 1.000000f );
const LVector4 LC_DarkPurple           ( 0.530000f, 0.120000f, 0.470000f, 1.000000f );
const LVector4 LC_NeonBlue             ( 0.300000f, 0.300000f, 1.000000f, 1.000000f );
const LVector4 LC_CoolCopper           ( 0.850000f, 0.530000f, 0.100000f, 1.000000f );
const LVector4 LC_MandarinOrange       ( 0.890000f, 0.470000f, 0.200000f, 1.000000f );
const LVector4 LC_LightWood            ( 0.910000f, 0.760000f, 0.650000f, 1.000000f );
const LVector4 LC_MediumWood           ( 0.650000f, 0.500000f, 0.390000f, 1.000000f );
const LVector4 LC_DarkWood             ( 0.520000f, 0.370000f, 0.260000f, 1.000000f );
const LVector4 LC_SpicyPink            ( 1.000000f, 0.110000f, 0.680000f, 1.000000f );
const LVector4 LC_SemiSweetChoc        ( 0.420000f, 0.260000f, 0.150000f, 1.000000f );
const LVector4 LC_BakersChoc           ( 0.360000f, 0.200000f, 0.090000f, 1.000000f );
const LVector4 LC_Flesh                ( 0.960000f, 0.800000f, 0.690000f, 1.000000f );
const LVector4 LC_NewTan               ( 0.920000f, 0.780000f, 0.620000f, 1.000000f );
const LVector4 LC_NewMidnightBlue      ( 0.000000f, 0.000000f, 0.610000f, 1.000000f );
const LVector4 LC_VeryDarkBrown        ( 0.350000f, 0.160000f, 0.140000f, 1.000000f );
const LVector4 LC_DarkBrown            ( 0.360000f, 0.250000f, 0.200000f, 1.000000f );
const LVector4 LC_DarkTan              ( 0.590000f, 0.410000f, 0.310000f, 1.000000f );
const LVector4 LC_GreenCopper          ( 0.320000f, 0.490000f, 0.460000f, 1.000000f );
const LVector4 LC_DkGreenCopper        ( 0.290000f, 0.460000f, 0.430000f, 1.000000f );
const LVector4 LC_DustyRose            ( 0.520000f, 0.390000f, 0.390000f, 1.000000f );
const LVector4 LC_HuntersGreen         ( 0.130000f, 0.370000f, 0.310000f, 1.000000f );
const LVector4 LC_Scarlet              ( 0.550000f, 0.090000f, 0.090000f, 1.000000f );
const LVector4 LC_MediumPurple         ( 0.730000f, 0.160000f, 0.960000f, 1.000000f );
const LVector4 LC_LightPurple          ( 0.870000f, 0.580000f, 0.980000f, 1.000000f );
const LVector4 LC_VeryLightPurple      ( 0.940000f, 0.810000f, 0.990000f, 1.000000f );
const LVector4 LC_Green                ( 0.000000f, 1.000000f, 0.000000f, 1.000000f );
const LVector4 LC_Olive                ( 0.000000f, 1.000000f, 1.000000f, 1.000000f );
const LVector4 LC_Purple               ( 1.000000f, 0.000000f, 1.000000f, 1.000000f );
const LVector4 LC_Teal                 ( 0.000000f, 1.000000f, 1.000000f, 1.000000f );
const LVector4 LC_Red                  ( 1.000000f, 0.000000f, 0.000000f, 1.000000f );
const LVector4 LC_Lime                 ( 0.000000f, 1.000000f, 0.000000f, 1.000000f );
const LVector4 LC_Yellow               ( 1.000000f, 1.000000f, 0.000000f, 1.000000f );
const LVector4 LC_Blue                 ( 0.000000f, 0.000000f, 1.000000f, 1.000000f );
const LVector4 LC_Fuchsia              ( 1.000000f, 0.000000f, 1.000000f, 1.000000f );
const LVector4 LC_Aqua                 ( 0.000000f, 1.000000f, 1.000000f, 1.000000f );
// console messages
const LVector4 LC_LinderdaumConsoleEM  ( 1.000000f, 1.000000f, 1.000000f, 0.900000f );
const LVector4 LC_LinderdaumConsoleLM  ( 0.700000f, 0.700000f, 0.700000f, 0.900000f );
const LVector4 LC_LinderdaumConsoleUM  ( 0.700000f, 1.000000f, 0.700000f, 0.900000f );
const LVector4 LC_LinderdaumConsoleIT  ( 0.700000f, 1.000000f, 0.700000f, 0.900000f );
const LVector4 LC_LinderdaumConsoleERR ( 1.000000f, 0.000000f, 0.000000f, 1.000000f );

#endif

/*
 * 12/07/2010
     Regenerated
 * 21/06/2007
     It's here
*/
