#!/usr/bin/python

import os
import sys
import platform

# regenerate 'makeconfig.py' for every project in Apps folder

Path    = "Apps"
Sep = os.path.sep
if Sep == "\\": Sep = "\\\\"
VCAutoPath = "Path(\"" + os.path.join("Tools", "VCauto.py") + "\")"

MainConfigName = "Solution/Configuration"

# add a nasty dot at the end for win32
if (platform.system() == "Windows"):
   MainConfigName = "Solution/Configuration."

Command = "os.system( "+VCAutoPath+" + \" -s Src -pr <_PROJECT_NAME_> -ver 2008 -ver 2010 -i \" + Path(\"Src\") + \" -i \" + Path(\"Src/Linderdaum\") + \" -i \" + Path(\"Src/ExtLibs\") + \" -m \" + Path(\"Solution/Targets.list\") + \" -c \" + Path(\"" + MainConfigName + "\") + \" -andr1 \" + Path(\"Solution/Targets.Android1\") + \" -andr2 \" + Path(\"Solution/Targets.Android2\") + \" -androut \" + (\"jni/Android.mk\") + \" -t makefile\")"

def WriteConfig( ConfigName, App ):
   f = open( ConfigName, "w" )
   f.write( "#! /usr/bin/python\n\n" )
   f.write( "#\n" )
   f.write( "#  Autogenerated via regenerateconfigs.py - changes will be lost\n" );
   f.write( "#\n" )
   f.write( "import os\n" )
   f.write( "import sys\n" )
   f.write( "\n" )
   f.write( "SDKPath = \"" +  os.path.join("..", "..") + "\"\n" )
   f.write( "\n" )
   f.write( "if os.getenv(\"LSDK_PATH\") is not None: SDKPath = os.getenv(\"LSDK_PATH\")\n" )
   f.write( "\n" )
   f.write( "print( \"Using LSDK_PATH: \", SDKPath )\n" )
   f.write( "\n" )
   f.write( "def Path( S ):\n" )
   f.write( "   return os.path.join( SDKPath, S )\n" )
   f.write( "\n" )
   f.write( str.replace( Command, "<_PROJECT_NAME_>", App ) )
   f.close()
   if (platform.system() != "Windows"):
      # Change permissions
      print("Writing ", ConfigName)
      os.system("chmod +x " + ConfigName)

argc = len(sys.argv)

if argc > 1:
   WriteConfig( sys.argv[1], sys.argv[2] );
else:
   for App in os.listdir( Path ):
      AppPath = os.path.join(Path, App)
      if os.path.isdir(AppPath):
         ConfigName = os.path.join(AppPath, "makeconfig.py" )
         if os.path.exists( ConfigName ):
            print("WriteConf: ", ConfigName)
            WriteConfig( ConfigName, App );
