#
# Part of the Linderdaum Engine
#

TARGET_PLATFORM := android-7

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_ARM_MODE := arm
LOCAL_MODULE     := LinderdaumEngineCore

LOCAL_C_INCLUDES += \
	$(LOCAL_PATH)/../../Src \
	$(LOCAL_PATH)/../../Src \
	$(LOCAL_PATH)/../../Src/ExtLibs \
	$(LOCAL_PATH)/../../Src/ExtLibs/CL \
	$(LOCAL_PATH)/../../Src/ExtLibs/DInput \
	$(LOCAL_PATH)/../../Src/ExtLibs/FMOD \
	$(LOCAL_PATH)/../../Src/ExtLibs/GL \
	$(LOCAL_PATH)/../../Src/ExtLibs/ModPlug \
	$(LOCAL_PATH)/../../Src/ExtLibs/OpenAL \
	$(LOCAL_PATH)/../../Src/ExtLibs/RSC \
	$(LOCAL_PATH)/../../Src/ExtLibs/Vorbis \
	$(LOCAL_PATH)/../../Src/ExtLibs/Vorbis/ogg \
	$(LOCAL_PATH)/../../Src/Generated \
	$(LOCAL_PATH)/../../Src/Generated/Exports \
	$(LOCAL_PATH)/../../Src/Generated/Globals \
	$(LOCAL_PATH)/../../Src/Generated/LAL \
	$(LOCAL_PATH)/../../Src/Generated/LCL \
	$(LOCAL_PATH)/../../Src/Generated/LGL \
	$(LOCAL_PATH)/../../Src/Generated/Serialization \
	$(LOCAL_PATH)/../../Src/Generated/VM \
	$(LOCAL_PATH)/../../Src/Linderdaum \
	$(LOCAL_PATH)/../../Src/Linderdaum/Audio \
	$(LOCAL_PATH)/../../Src/Linderdaum/Core \
	$(LOCAL_PATH)/../../Src/Linderdaum/Core/RTTI \
	$(LOCAL_PATH)/../../Src/Linderdaum/Core/VFS \
	$(LOCAL_PATH)/../../Src/Linderdaum/Geometry \
	$(LOCAL_PATH)/../../Src/Linderdaum/GUI \
	$(LOCAL_PATH)/../../Src/Linderdaum/GUI/ComCtl \
	$(LOCAL_PATH)/../../Src/Linderdaum/GUI/Transitions \
	$(LOCAL_PATH)/../../Src/Linderdaum/Images \
	$(LOCAL_PATH)/../../Src/Linderdaum/Input \
	$(LOCAL_PATH)/../../Src/Linderdaum/Math \
	$(LOCAL_PATH)/../../Src/Linderdaum/Network \
	$(LOCAL_PATH)/../../Src/Linderdaum/Physics \
	$(LOCAL_PATH)/../../Src/Linderdaum/Renderer \
	$(LOCAL_PATH)/../../Src/Linderdaum/Renderer/CL \
	$(LOCAL_PATH)/../../Src/Linderdaum/Renderer/DX11 \
	$(LOCAL_PATH)/../../Src/Linderdaum/Renderer/GL \
	$(LOCAL_PATH)/../../Src/Linderdaum/Renderer/Soft \
	$(LOCAL_PATH)/../../Src/Linderdaum/Resources \
	$(LOCAL_PATH)/../../Src/Linderdaum/Scene \
	$(LOCAL_PATH)/../../Src/Linderdaum/Scene/Heightmaps \
	$(LOCAL_PATH)/../../Src/Linderdaum/Scene/Particles \
	$(LOCAL_PATH)/../../Src/Linderdaum/Scene/Postprocess \
	$(LOCAL_PATH)/../../Src/Linderdaum/Scene/Terrain \
	$(LOCAL_PATH)/../../Src/Linderdaum/UnitTests \
	$(LOCAL_PATH)/../../Src/Linderdaum/UnitTests/Tests \
	$(LOCAL_PATH)/../../Src/Linderdaum/Utils \
	$(LOCAL_PATH)/../../Src/Linderdaum/VisualScene \
	$(LOCAL_PATH)/../../Src/Linderdaum/World \
	$(LOCAL_PATH)/../../Src/Linderdaum/World/AI \

LOCAL_SRC_FILES += \
	../../Src/Generated/Exports/Exports_Core.cpp \
	../../Src/Generated/Exports/ExpReg_Core1.cpp \
	../../Src/Generated/Exports/ExpReg_Core2.cpp \
	../../Src/Generated/Exports/ExpReg_Core3.cpp \
	../../Src/Generated/Exports/ExpReg_Core4.cpp \
	../../Src/Generated/Exports/ExpReg_Core5.cpp \
	../../Src/Generated/Exports/ExpReg_Core6.cpp \
	../../Src/Generated/Exports/ExpReg_Core7.cpp \
	../../Src/Generated/Globals/ColorRegistration.cpp \
	../../Src/Generated/Globals/KeySymbolsRegistration.cpp \
	../../Src/Generated/Globals/LColors.cpp \
	../../Src/Generated/LAL/LAL.cpp \
	../../Src/Generated/LCL/LCL.cpp \
	../../Src/Generated/LGL/LGL.cpp \
	../../Src/Generated/LGL/LGLTracer.cpp \
	../../Src/Generated/Serialization/Serialization_LinderdaumCore.cpp \
	../../Src/Linderdaum/Audio/Audio.cpp \
	../../Src/Linderdaum/Audio/Audio_FMOD.cpp \
	../../Src/Linderdaum/Audio/Audio_OpenAL.cpp \
	../../Src/Linderdaum/Audio/MOD.cpp \
	../../Src/Linderdaum/Audio/OGG.cpp \
	../../Src/Linderdaum/Core/Console.cpp \
	../../Src/Linderdaum/Core/CVars.cpp \
	../../Src/Linderdaum/Core/iObject.cpp \
	../../Src/Linderdaum/Core/Linker.cpp \
	../../Src/Linderdaum/Core/Logger.cpp \
	../../Src/Linderdaum/Core/RTTI/Field.cpp \
	../../Src/Linderdaum/Core/RTTI/iStaticClass.cpp \
	../../Src/Linderdaum/Core/RTTI/Property.cpp \
	../../Src/Linderdaum/Core/RTTI/State.cpp \
	../../Src/Linderdaum/Core/Script.cpp \
	../../Src/Linderdaum/Core/ScriptCompiler.cpp \
	../../Src/Linderdaum/Core/UUID.cpp \
	../../Src/Linderdaum/Core/VFS/Archive.cpp \
	../../Src/Linderdaum/Core/VFS/Files.cpp \
	../../Src/Linderdaum/Core/VFS/FileSystem.cpp \
	../../Src/Linderdaum/Core/VFS/libcompress.c \
	../../Src/Linderdaum/Core/VFS/ML.cpp \
	../../Src/Linderdaum/Core/VFS/MountPoint.cpp \
	../../Src/Linderdaum/Core/VFS/pugixml.cpp \
	../../Src/Linderdaum/Environment.cpp \
	../../Src/Linderdaum/Geometry/Animation.cpp \
	../../Src/Linderdaum/Geometry/ASE.cpp \
	../../Src/Linderdaum/Geometry/Geom.cpp \
	../../Src/Linderdaum/Geometry/GeomServ.cpp \
	../../Src/Linderdaum/Geometry/Joints.cpp \
	../../Src/Linderdaum/Geometry/LCM.cpp \
	../../Src/Linderdaum/Geometry/MD5.cpp \
	../../Src/Linderdaum/Geometry/Mesh.cpp \
	../../Src/Linderdaum/Geometry/Surfaces.cpp \
	../../Src/Linderdaum/Geometry/VAMender.cpp \
	../../Src/Linderdaum/Geometry/VertexAttribs.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_BorderPanel.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Bubbles.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Button.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Checkable.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_CheckBox.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_ColorDial.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_DialogWindow.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_FSGraph.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Gauge.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_InputLine.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_ListBox.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Memo.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_MtxView.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Page.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Panel.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_PushButton.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_RadioButton.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_RadioGroup.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_SceneView.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Scroller.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Sidebar.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Slider.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Splitters.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_StaticRect.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_StaticWidget.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_StdConsole.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_TabControl.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_TransitionPage.cpp \
	../../Src/Linderdaum/GUI/ComCtl/I_Window.cpp \
	../../Src/Linderdaum/GUI/FlowUI.cpp \
	../../Src/Linderdaum/GUI/GUIDesktop.cpp \
	../../Src/Linderdaum/GUI/GUIManager.cpp \
	../../Src/Linderdaum/GUI/iGUIRegion.cpp \
	../../Src/Linderdaum/GUI/iGUIResponder.cpp \
	../../Src/Linderdaum/GUI/iGUIView.cpp \
	../../Src/Linderdaum/GUI/Transitions/I_CrossFade.cpp \
	../../Src/Linderdaum/GUI/Transitions/I_Slide.cpp \
	../../Src/Linderdaum/Images/Bitmap.cpp \
	../../Src/Linderdaum/Images/FI_Utils.cpp \
	../../Src/Linderdaum/Images/Guillotine.cpp \
	../../Src/Linderdaum/Images/Image.cpp \
	../../Src/Linderdaum/Images/ImageCache.cpp \
	../../Src/Linderdaum/Images/ImageList.cpp \
	../../Src/Linderdaum/Images/ImgLoad.cpp \
	../../Src/Linderdaum/Images/RAW.cpp \
	../../Src/Linderdaum/Images/TextRenderer.cpp \
	../../Src/Linderdaum/Images/VolumeLib.cpp \
	../../Src/Linderdaum/Input/Gestures.cpp \
	../../Src/Linderdaum/Input/Gestures2.cpp \
	../../Src/Linderdaum/Input/Input.cpp \
	../../Src/Linderdaum/Input/NetDevices.cpp \
	../../Src/Linderdaum/Input/OSInput.cpp \
	../../Src/Linderdaum/Input/ScreenJoystick.cpp \
	../../Src/Linderdaum/LString.cpp \
	../../Src/Linderdaum/Math/Collision.cpp \
	../../Src/Linderdaum/Math/LAABB.cpp \
	../../Src/Linderdaum/Math/LBox.cpp \
	../../Src/Linderdaum/Math/LCurve.cpp \
	../../Src/Linderdaum/Math/LFFT.cpp \
	../../Src/Linderdaum/Math/LFrustum.cpp \
	../../Src/Linderdaum/Math/LGeomUtils.cpp \
	../../Src/Linderdaum/Math/LGraph.cpp \
	../../Src/Linderdaum/Math/LMathStrings.cpp \
	../../Src/Linderdaum/Math/LMatrix.cpp \
	../../Src/Linderdaum/Math/LOBB.cpp \
	../../Src/Linderdaum/Math/LPoly.cpp \
	../../Src/Linderdaum/Math/LProjection.cpp \
	../../Src/Linderdaum/Math/LRandom.cpp \
	../../Src/Linderdaum/Math/LSphere.cpp \
	../../Src/Linderdaum/Math/LTransform.cpp \
	../../Src/Linderdaum/Math/LVector.cpp \
	../../Src/Linderdaum/Network/HTTP.cpp \
	../../Src/Linderdaum/Network/Network.cpp \
	../../Src/Linderdaum/Physics/BodyControllers.cpp \
	../../Src/Linderdaum/Physics/BoxLite.cpp \
	../../Src/Linderdaum/Physics/BoxScene.cpp \
	../../Src/Linderdaum/Physics/Collider.cpp \
	../../Src/Linderdaum/Physics/CollisionIntervals.cpp \
	../../Src/Linderdaum/Physics/CollisionShape.cpp \
	../../Src/Linderdaum/Physics/Control.cpp \
	../../Src/Linderdaum/Physics/RigidBody.cpp \
	../../Src/Linderdaum/Physics/SimplePhysics.cpp \
	../../Src/Linderdaum/Renderer/Canvas.cpp \
	../../Src/Linderdaum/Renderer/CL/CLContext.cpp \
	../../Src/Linderdaum/Renderer/DX11/DX11RenderContext.cpp \
	../../Src/Linderdaum/Renderer/GL/GLAPIContainer.cpp \
	../../Src/Linderdaum/Renderer/GL/GLBuffer.cpp \
	../../Src/Linderdaum/Renderer/GL/GLDebug.cpp \
	../../Src/Linderdaum/Renderer/GL/GLFrameBuffer.cpp \
	../../Src/Linderdaum/Renderer/GL/GLQuery.cpp \
	../../Src/Linderdaum/Renderer/GL/GLRenderContext.cpp \
	../../Src/Linderdaum/Renderer/GL/GLSL.cpp \
	../../Src/Linderdaum/Renderer/GL/GLTexture.cpp \
	../../Src/Linderdaum/Renderer/GL/GLVertexArray.cpp \
	../../Src/Linderdaum/Renderer/iRenderContext.cpp \
	../../Src/Linderdaum/Renderer/iShaderProgram.cpp \
	../../Src/Linderdaum/Renderer/iTexture.cpp \
	../../Src/Linderdaum/Renderer/iVertexArray.cpp \
	../../Src/Linderdaum/Renderer/RenderState.cpp \
	../../Src/Linderdaum/Renderer/Soft/SoftFrameBuffer.cpp \
	../../Src/Linderdaum/Renderer/Soft/SoftRenderContext.cpp \
	../../Src/Linderdaum/Renderer/VolumeRenderer.cpp \
	../../Src/Linderdaum/Resources/iResource.cpp \
	../../Src/Linderdaum/Resources/ResourcesManager.cpp \
	../../Src/Linderdaum/Resources/VFW.cpp \
	../../Src/Linderdaum/Scene/CSM.cpp \
	../../Src/Linderdaum/Scene/GameCamera.cpp \
	../../Src/Linderdaum/Scene/Heightmaps/HeightMapFacetter.cpp \
	../../Src/Linderdaum/Scene/Heightmaps/LHeightMap.cpp \
	../../Src/Linderdaum/Scene/iUpdater.cpp \
	../../Src/Linderdaum/Scene/LVLib.cpp \
	../../Src/Linderdaum/Scene/Material.cpp \
	../../Src/Linderdaum/Scene/Particles/GPUParticles.cpp \
	../../Src/Linderdaum/Scene/Particles/ParticleSystem.cpp \
	../../Src/Linderdaum/Scene/Postprocess/ASSAO.cpp \
	../../Src/Linderdaum/Scene/Postprocess/FeedbackScreen.cpp \
	../../Src/Linderdaum/Scene/Postprocess/Filter.cpp \
	../../Src/Linderdaum/Scene/Postprocess/HDRPP.cpp \
	../../Src/Linderdaum/Scene/Postprocess/iPostprocessor.cpp \
	../../Src/Linderdaum/Scene/Postprocess/MLAA.cpp \
	../../Src/Linderdaum/Scene/Postprocess/RenderingTechnique.cpp \
	../../Src/Linderdaum/Scene/Scene.cpp \
	../../Src/Linderdaum/Scene/Terrain/Terrain.cpp \
	../../Src/Linderdaum/SysEnv.cpp \
	../../Src/Linderdaum/UnitTests/Tests.cpp \
	../../Src/Linderdaum/Utils/DateTime.cpp \
	../../Src/Linderdaum/Utils/Event.cpp \
	../../Src/Linderdaum/Utils/Exceptions.cpp \
	../../Src/Linderdaum/Utils/LArray.cpp \
	../../Src/Linderdaum/Utils/Library.cpp \
	../../Src/Linderdaum/Utils/Localizer.cpp \
	../../Src/Linderdaum/Utils/Screen.cpp \
	../../Src/Linderdaum/Utils/Thread.cpp \
	../../Src/Linderdaum/Utils/Utils.cpp \
	../../Src/Linderdaum/Utils/Viewport.cpp \
	../../Src/Linderdaum/VisualScene/CameraPositioner.cpp \
	../../Src/Linderdaum/VisualScene/Edit.cpp \
	../../Src/Linderdaum/VisualScene/Gizmos.cpp \
	../../Src/Linderdaum/VisualScene/Prefab.cpp \
	../../Src/Linderdaum/VisualScene/Trajectory.cpp \
	../../Src/Linderdaum/VisualScene/VisualCamera.cpp \
	../../Src/Linderdaum/VisualScene/VisualGraph.cpp \
	../../Src/Linderdaum/VisualScene/VisualObject.cpp \
	../../Src/Linderdaum/VisualScene/VisualProjector.cpp \
	../../Src/Linderdaum/VisualScene/VisualRenderables.cpp \
	../../Src/Linderdaum/VisualScene/VisualScene.cpp \
	../../Src/Linderdaum/World/AI/Behaviour.cpp \
	../../Src/Linderdaum/World/AI/Pathfinder.cpp \
	../../Src/Linderdaum/World/Entity.cpp \
	../../Src/Linderdaum/World/HighScores.cpp \
	../../Src/Linderdaum/World/iActor.cpp \
	../../Src/Linderdaum/World/World.cpp \


LOCAL_CFLAGS   := -mfpu=vfp -mfloat-abi=softfp -O3 -Werror -DANDROID -DDISABLE_IMPORTGL -D_DISABLE_TUNNELLERS_ -D_DISABLE_METHODS_ -DDISABLE_GUARD_UNGUARD_MECHANISM -isystem $(SYSROOT)/usr/include/ 

LOCAL_LDLIBS     := -llog -lGLESv2 -Wl,-s

include $(BUILD_STATIC_LIBRARY)
