#! /usr/bin/python

#
#  Autogenerated via regenerateconfigs.py - changes will be lost
#
import os
import sys

SDKPath = "..\.."

if os.getenv("LSDK_PATH") is not None: SDKPath = os.getenv("LSDK_PATH")

print( "Using LSDK_PATH: ", SDKPath )

def Path( S ):
   return os.path.join( SDKPath, S )

os.system( Path("Tools\VCauto.py") + " -s Src -pr Test_Android -ver 2008 -ver 2010 -i " + Path("Src") + " -i " + Path("Src/Linderdaum") + " -i " + Path("Src/ExtLibs") + " -m " + Path("Solution/Targets.list") + " -c " + Path("Solution/Configuration.") + " -andr1 " + Path("Solution/Targets.Android1") + " -andr2 " + Path("Solution/Targets.Android2") + " -androut " + ("jni/Android.mk") + " -t makefile")