#include "Engine.h"

#include "Tests.h"

#include "Core/Logger.h"

// tests
#include "Tests/Test_2.h"
#include "Tests/Test_3.h"
#include "Tests/Test_5.h"
#include "Tests/Test_6.h"
#include "Tests/Test_7.h"
#include "Tests/Test_9.h"
#include "Tests/Test_8.h"
#include "Tests/Test_1.h"
#include "Tests/Test_4.h"
#include "Tests/Test_10.h"
#include "Tests/Test_11.h"


void DoAllTests( sEnvironment* Env )
{
	Test_1( Env );
	Test_2( Env );
	Test_3( Env );
	Test_4( Env );
	Test_5( Env );
	Test_6( Env );
	Test_7( Env );
	// Test_8(Env);
	Test_9( Env );
	Test_10( Env );
	Test_11( Env );
}

/*
 * 22/03/2005
     Autogenerated via TestGen 0.1
*/

